// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'torrent.dart';

// These functions are ignored because they are not marked as `pub`: `pursue_fetches`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Every collection this device knows about, from both sources, joined.
Future<List<CollectionInfo>> listCollections() =>
    RustLib.instance.api.crateCollectionsListCollections();

/// Whether the BitTorrent engine has finished starting.
///
/// Exposed so the UI can tell the difference between "this collection has
/// nothing to fetch" and "the engine hasn't come up yet, so nothing is being
/// shared *right now*". Those two look identical otherwise, which is exactly
/// the ambiguity that made a freshly-launched app look broken. Never blocks —
/// `sync_address`/`ensure_listener` warms the session in the background.
Future<bool> engineReady() =>
    RustLib.instance.api.crateCollectionsEngineReady();

/// Creates a new shared collection (empty) and persists it. This device
/// becomes its first collaborator, as admin.
Future<CollectionInfo> createCollection({required String name}) =>
    RustLib.instance.api.crateCollectionsCreateCollection(name: name);

/// Creates a shared collection *and* seeds `files` into it as its first
/// manifest entry — the "share something" flow, which previously produced a
/// bare torrent with no invite code and therefore nothing to share.
Future<CollectionInfo> createCollectionWithMedia(
        {required String name, required List<NewFile> files}) =>
    RustLib.instance.api
        .crateCollectionsCreateCollectionWithMedia(name: name, files: files);

/// Joins a shared collection from an invite code. Returns immediately; the
/// first sync with the inviter runs in the background (see the note in
/// [`native::join_collection`]).
Future<CollectionInfo> joinCollection(
        {required String inviteCode, required String displayName}) =>
    RustLib.instance.api.crateCollectionsJoinCollection(
        inviteCode: inviteCode, displayName: displayName);

/// Adds local files to a shared collection as one new signed manifest entry
/// with its own torrent. This is how a collection grows.
Future<CollectionInfo> addMediaToCollection(
        {required String collectionId,
        required String label,
        required List<NewFile> files}) =>
    RustLib.instance.api.crateCollectionsAddMediaToCollection(
        collectionId: collectionId, label: label, files: files);

/// Starts downloading every not-yet-fetched manifest entry, handing librqbit
/// the peer addresses learned during sync as direct connection hints.
/// Returns how many entries were started.
Future<int> fetchCollectionMedia({required String collectionId}) =>
    RustLib.instance.api
        .crateCollectionsFetchCollectionMedia(collectionId: collectionId);

/// Brings the engine up: the sync listener, the convergence loop, and the
/// BitTorrent session warming in the background.
///
/// Explicit, because it used to happen as a side effect of the UI asking for
/// the collection list — so the app's networking began when a screen first
/// drew, and an invite generated before that drew carried no address for
/// anyone to reach.
Future<void> startEngine() =>
    RustLib.instance.api.crateCollectionsStartEngine();

/// Tells the engine whether anyone is looking, so it can stop reaching for
/// the network when nobody is. Called from the app's lifecycle observer.
Future<void> setActive({required bool active}) =>
    RustLib.instance.api.crateCollectionsSetActive(active: active);

/// One full manifest sync with a peer, for a shared collection.
Future<CollectionInfo> syncCollection(
        {required String collectionId, required String peerAddr}) =>
    RustLib.instance.api.crateCollectionsSyncCollection(
        collectionId: collectionId, peerAddr: peerAddr);

/// Forgets a collection on this device. For a `Shared` one that means
/// dropping it from `collections.json` (other collaborators keep their
/// copies — there's no "delete for everyone" in a grow-only design); for a
/// `Torrent` one it means removing it from the session. Downloaded files are
/// left on disk either way.
Future<void> deleteCollection({required String collectionId}) =>
    RustLib.instance.api
        .crateCollectionsDeleteCollection(collectionId: collectionId);

/// This device's manifest-sync endpoints (LAN, plus public IP when
/// discoverable), comma-separated. Starts the sync listener as a side
/// effect, so calling it makes this device reachable.
Future<String> syncAddress() =>
    RustLib.instance.api.crateCollectionsSyncAddress();

/// What's on disk, resolved back to the collections the app knows about.
Future<List<StorageEntry>> storageBreakdown() =>
    RustLib.instance.api.crateCollectionsStorageBreakdown();

class CollaboratorInfo {
  final String deviceId;
  final String displayName;
  final bool isAdmin;

  const CollaboratorInfo({
    required this.deviceId,
    required this.displayName,
    required this.isAdmin,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ displayName.hashCode ^ isAdmin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollaboratorInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isAdmin == other.isAdmin;
}

class CollectionInfo {
  /// A shared collection's `CollectionId`, or a torrent's info-hash.
  /// Opaque to Flutter; pass it back to the functions below.
  final String id;
  final String name;
  final CollectionKind kind;

  /// Paste-able invite code — `Shared` collections only. See
  /// [`invite_code_for`] for the format and why it's hex-wrapped.
  final String? inviteCode;
  final List<CollaboratorInfo> collaborators;

  /// Every file across every fetched manifest entry, plus one placeholder
  /// per not-yet-fetched entry.
  final List<MediaInfo> media;

  /// 0.0..=1.0 across all *fetched* bytes. Entries that haven't been
  /// fetched contribute nothing to either side of the ratio — they're
  /// counted by [`pending_media`](Self::pending_media) instead, since
  /// their size isn't knowable until the torrent's metadata arrives.
  final double progress;
  final BigInt totalBytes;
  final BigInt downloadedBytes;
  final BigInt uploadedBytes;
  final double downloadMbps;
  final double uploadMbps;

  /// Currently-connected peers, summed across this collection's torrents.
  final int livePeers;

  /// Manifest entries with no local torrent yet — "known but not fetched".
  final int pendingMedia;

  /// Seconds until the download finishes at the current rate, or `None`
  /// when there is nothing meaningful to say: nothing left to fetch, or
  /// nothing moving to extrapolate from.
  ///
  /// Downloads only. Seeding has no endpoint to count down to — a peer's
  /// remaining bytes are their business and not visible from here — so an
  /// upload "ETA" would be a fabricated number.
  final BigInt? etaSecs;

  /// Coarse status for display: `seeding` / `downloading` / `pending` /
  /// `empty`. Derived here rather than in the UI so both kinds of
  /// collection describe themselves the same way.
  final String state;

  const CollectionInfo({
    required this.id,
    required this.name,
    required this.kind,
    this.inviteCode,
    required this.collaborators,
    required this.media,
    required this.progress,
    required this.totalBytes,
    required this.downloadedBytes,
    required this.uploadedBytes,
    required this.downloadMbps,
    required this.uploadMbps,
    required this.livePeers,
    required this.pendingMedia,
    this.etaSecs,
    required this.state,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      inviteCode.hashCode ^
      collaborators.hashCode ^
      media.hashCode ^
      progress.hashCode ^
      totalBytes.hashCode ^
      downloadedBytes.hashCode ^
      uploadedBytes.hashCode ^
      downloadMbps.hashCode ^
      uploadMbps.hashCode ^
      livePeers.hashCode ^
      pendingMedia.hashCode ^
      etaSecs.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          inviteCode == other.inviteCode &&
          collaborators == other.collaborators &&
          media == other.media &&
          progress == other.progress &&
          totalBytes == other.totalBytes &&
          downloadedBytes == other.downloadedBytes &&
          uploadedBytes == other.uploadedBytes &&
          downloadMbps == other.downloadMbps &&
          uploadMbps == other.uploadMbps &&
          livePeers == other.livePeers &&
          pendingMedia == other.pendingMedia &&
          etaSecs == other.etaSecs &&
          state == other.state;
}

/// What kind of collection this is — the two ways one can come into
/// existence. Both render identically; they differ in what you can *do*
/// with them (only `Shared` has an invite code and can grow).
enum CollectionKind {
  /// Invite-based and growable: has an invite code, collaborators, and a
  /// signed manifest that gains entries over time.
  shared,

  /// A single plain torrent added by magnet link — no invite, no
  /// collaborators, fixed contents.
  torrent,
  ;
}

class MediaInfo {
  final String name;

  /// The label of the *manifest entry* this file belongs to, as signed by
  /// whoever added it — the batch name, not this file's name. Several files
  /// share one. For a plain torrent it's the torrent's own name.
  ///
  /// Carried explicitly because flattening a collection's entries into a
  /// file list otherwise loses it entirely, leaving the UI to guess an
  /// entry's label from its first file.
  final String entryName;

  /// The info-hash of the torrent (i.e. the manifest entry) this file
  /// belongs to — several files can share one.
  final String infoHash;

  /// Real on-disk location, once the file is complete. `None` while
  /// downloading, and always `None` for a not-yet-fetched entry.
  final String? absolutePath;
  final BigInt lengthBytes;
  final BigInt downloadedBytes;
  final double progress;

  /// `false` when this stands for a whole manifest entry whose torrent
  /// isn't in the session yet — tap to fetch.
  final bool fetched;

  /// Device id of the collaborator who added it (`Shared` only).
  final String? addedBy;

  const MediaInfo({
    required this.name,
    required this.entryName,
    required this.infoHash,
    this.absolutePath,
    required this.lengthBytes,
    required this.downloadedBytes,
    required this.progress,
    required this.fetched,
    this.addedBy,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      entryName.hashCode ^
      infoHash.hashCode ^
      absolutePath.hashCode ^
      lengthBytes.hashCode ^
      downloadedBytes.hashCode ^
      progress.hashCode ^
      fetched.hashCode ^
      addedBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          entryName == other.entryName &&
          infoHash == other.infoHash &&
          absolutePath == other.absolutePath &&
          lengthBytes == other.lengthBytes &&
          downloadedBytes == other.downloadedBytes &&
          progress == other.progress &&
          fetched == other.fetched &&
          addedBy == other.addedBy;
}

/// One item under the download directory, joined against whichever
/// collection actually claims it — the same join [`list_collections`] does
/// between the persisted manifest and the live session, applied to
/// `torrent::storage_breakdown`'s raw filesystem walk instead of to the
/// session's torrent list.
///
/// `collection_id`/`collection_name` are `None` when nothing in the app's
/// own state claims this path — the common case is a deleted collection's
/// leftovers: [`delete_collection`] deliberately leaves downloaded files on
/// disk, so a folder can easily outlive every record of what it was.
class StorageEntry {
  final String name;
  final BigInt bytes;
  final String path;
  final String? collectionId;
  final String? collectionName;

  const StorageEntry({
    required this.name,
    required this.bytes,
    required this.path,
    this.collectionId,
    this.collectionName,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      bytes.hashCode ^
      path.hashCode ^
      collectionId.hashCode ^
      collectionName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bytes == other.bytes &&
          path == other.path &&
          collectionId == other.collectionId &&
          collectionName == other.collectionName;
}
