// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'torrent.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Creates a new collab collection and persists it. This device is added
/// as the first collaborator (an admin — see the backend README's still-
/// open moderation-semantics question for why this isn't enforced beyond
/// local display).
Future<CollabCollectionInfo> createCollabCollection({required String name}) =>
    RustLib.instance.api.crateCollabCreateCollabCollection(name: name);

/// Joins a collection from an invite code someone else shared. Adds this
/// device as a `Member` collaborator; the manifest starts empty until a
/// later phase's sync protocol pulls in what other collaborators already
/// added.
Future<CollabCollectionInfo> joinCollabCollection(
        {required String inviteCode, required String displayName}) =>
    RustLib.instance.api.crateCollabJoinCollabCollection(
        inviteCode: inviteCode, displayName: displayName);

/// Adds a new batch of local files as one new signed manifest entry —
/// creates its own torrent (own info-hash), self-seeded exactly like
/// `torrent::create_collection`, and appends a manifest entry pointing at
/// it. This is how a Collection grows without ever needing one torrent's
/// info-hash to stand for the *whole* collection's identity.
Future<CollabCollectionInfo> addMediaToCollabCollection(
        {required String collectionId,
        required String label,
        required List<NewFile> files}) =>
    RustLib.instance.api.crateCollabAddMediaToCollabCollection(
        collectionId: collectionId, label: label, files: files);

/// Every collab collection this device knows about (created or joined).
Future<List<CollabCollectionInfo>> listCollabCollections() =>
    RustLib.instance.api.crateCollabListCollabCollections();

class CollabCollectionInfo {
  final String id;
  final String name;

  /// Paste-able invite: encodes both the collection name and its invite
  /// secret, so `join_collab_collection` only needs this one string.
  final String inviteCode;
  final List<CollaboratorInfo> collaborators;
  final List<ManifestEntryInfo> media;

  const CollabCollectionInfo({
    required this.id,
    required this.name,
    required this.inviteCode,
    required this.collaborators,
    required this.media,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      inviteCode.hashCode ^
      collaborators.hashCode ^
      media.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollabCollectionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          inviteCode == other.inviteCode &&
          collaborators == other.collaborators &&
          media == other.media;
}

class CollaboratorInfo {
  final String deviceId;
  final String displayName;
  final bool isAdmin;

  const CollaboratorInfo({
    required this.deviceId,
    required this.displayName,
    required this.isAdmin,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ displayName.hashCode ^ isAdmin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollaboratorInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isAdmin == other.isAdmin;
}

class ManifestEntryInfo {
  final String infoHash;
  final String name;
  final String addedBy;
  final PlatformInt64 addedAtUnixMs;

  const ManifestEntryInfo({
    required this.infoHash,
    required this.name,
    required this.addedBy,
    required this.addedAtUnixMs,
  });

  @override
  int get hashCode =>
      infoHash.hashCode ^
      name.hashCode ^
      addedBy.hashCode ^
      addedAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManifestEntryInfo &&
          runtimeType == other.runtimeType &&
          infoHash == other.infoHash &&
          name == other.name &&
          addedBy == other.addedBy &&
          addedAtUnixMs == other.addedAtUnixMs;
}
