// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_identity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Loads the persisted identity, generating and saving one on first call.
Future<DeviceIdentityInfo> deviceIdentity() =>
    RustLib.instance.api.crateDeviceDeviceIdentity();

/// Renames this device's identity (display name only — the keypair itself
/// never changes).
Future<DeviceIdentityInfo> setNickname({required String nickname}) =>
    RustLib.instance.api.crateDeviceSetNickname(nickname: nickname);

class DeviceIdentityInfo {
  final String deviceId;
  final String nickname;

  const DeviceIdentityInfo({
    required this.deviceId,
    required this.nickname,
  });

  @override
  int get hashCode => deviceId.hashCode ^ nickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceIdentityInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          nickname == other.nickname;
}
