// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';
import 'collab.dart';
import 'dart:async';
import 'dart:convert';
import 'device.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'torrent.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1235616158;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'backend',
    ioDirectory: 'rust/backend/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<CollabCollectionInfo> crateCollabAddMediaToCollabCollection(
      {required String collectionId,
      required String label,
      required List<NewFile> files});

  Future<TorrentInfo> crateTorrentAddTorrentFromFileBytes(
      {required List<int> bytes});

  Future<TorrentInfo> crateTorrentAddTorrentFromMagnet(
      {required String magnetOrHash});

  Future<String> crateCollabCollabSyncAddress();

  Future<CollabCollectionInfo> crateCollabCreateCollabCollection(
      {required String name});

  Future<TorrentInfo> crateTorrentCreateCollection(
      {required String name, required List<NewFile> files});

  Future<DeviceIdentityInfo> crateDeviceDeviceIdentity();

  String crateBridgeGetVersion();

  Future<CollabCollectionInfo> crateCollabJoinCollabCollection(
      {required String inviteCode, required String displayName});

  Future<List<CollabCollectionInfo>> crateCollabListCollabCollections();

  Future<List<TorrentInfo>> crateTorrentListTorrents();

  Future<String> crateTorrentOutputDir();

  Future<DeviceIdentityInfo> crateDeviceSetNickname({required String nickname});

  Future<void> crateTorrentSetUploadLimitBps({int? bytesPerSec});

  Future<BigInt> crateTorrentStorageUsageBytes();

  Future<CollabCollectionInfo> crateCollabSyncCollabCollection(
      {required String collectionId, required String peerAddr});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CollabCollectionInfo> crateCollabAddMediaToCollabCollection(
      {required String collectionId,
      required String label,
      required List<NewFile> files}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(collectionId, serializer);
        sse_encode_String(label, serializer);
        sse_encode_list_new_file(files, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_collab_collection_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateCollabAddMediaToCollabCollectionConstMeta,
      argValues: [collectionId, label, files],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateCollabAddMediaToCollabCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "add_media_to_collab_collection",
        argNames: ["collectionId", "label", "files"],
      );

  @override
  Future<TorrentInfo> crateTorrentAddTorrentFromFileBytes(
      {required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentAddTorrentFromFileBytesConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentAddTorrentFromFileBytesConstMeta =>
      const TaskConstMeta(
        debugName: "add_torrent_from_file_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<TorrentInfo> crateTorrentAddTorrentFromMagnet(
      {required String magnetOrHash}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(magnetOrHash, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentAddTorrentFromMagnetConstMeta,
      argValues: [magnetOrHash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentAddTorrentFromMagnetConstMeta =>
      const TaskConstMeta(
        debugName: "add_torrent_from_magnet",
        argNames: ["magnetOrHash"],
      );

  @override
  Future<String> crateCollabCollabSyncAddress() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateCollabCollabSyncAddressConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateCollabCollabSyncAddressConstMeta =>
      const TaskConstMeta(
        debugName: "collab_sync_address",
        argNames: [],
      );

  @override
  Future<CollabCollectionInfo> crateCollabCreateCollabCollection(
      {required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_collab_collection_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateCollabCreateCollabCollectionConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateCollabCreateCollabCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "create_collab_collection",
        argNames: ["name"],
      );

  @override
  Future<TorrentInfo> crateTorrentCreateCollection(
      {required String name, required List<NewFile> files}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_list_new_file(files, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentCreateCollectionConstMeta,
      argValues: [name, files],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentCreateCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "create_collection",
        argNames: ["name", "files"],
      );

  @override
  Future<DeviceIdentityInfo> crateDeviceDeviceIdentity() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_device_identity_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateDeviceDeviceIdentityConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateDeviceDeviceIdentityConstMeta => const TaskConstMeta(
        debugName: "device_identity",
        argNames: [],
      );

  @override
  String crateBridgeGetVersion() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateBridgeGetVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeGetVersionConstMeta => const TaskConstMeta(
        debugName: "get_version",
        argNames: [],
      );

  @override
  Future<CollabCollectionInfo> crateCollabJoinCollabCollection(
      {required String inviteCode, required String displayName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inviteCode, serializer);
        sse_encode_String(displayName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_collab_collection_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateCollabJoinCollabCollectionConstMeta,
      argValues: [inviteCode, displayName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateCollabJoinCollabCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "join_collab_collection",
        argNames: ["inviteCode", "displayName"],
      );

  @override
  Future<List<CollabCollectionInfo>> crateCollabListCollabCollections() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_collab_collection_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateCollabListCollabCollectionsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateCollabListCollabCollectionsConstMeta =>
      const TaskConstMeta(
        debugName: "list_collab_collections",
        argNames: [],
      );

  @override
  Future<List<TorrentInfo>> crateTorrentListTorrents() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentListTorrentsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentListTorrentsConstMeta => const TaskConstMeta(
        debugName: "list_torrents",
        argNames: [],
      );

  @override
  Future<String> crateTorrentOutputDir() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentOutputDirConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentOutputDirConstMeta => const TaskConstMeta(
        debugName: "output_dir",
        argNames: [],
      );

  @override
  Future<DeviceIdentityInfo> crateDeviceSetNickname(
      {required String nickname}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nickname, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_device_identity_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateDeviceSetNicknameConstMeta,
      argValues: [nickname],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateDeviceSetNicknameConstMeta => const TaskConstMeta(
        debugName: "set_nickname",
        argNames: ["nickname"],
      );

  @override
  Future<void> crateTorrentSetUploadLimitBps({int? bytesPerSec}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_box_autoadd_u_32(bytesPerSec, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentSetUploadLimitBpsConstMeta,
      argValues: [bytesPerSec],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentSetUploadLimitBpsConstMeta =>
      const TaskConstMeta(
        debugName: "set_upload_limit_bps",
        argNames: ["bytesPerSec"],
      );

  @override
  Future<BigInt> crateTorrentStorageUsageBytes() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentStorageUsageBytesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentStorageUsageBytesConstMeta =>
      const TaskConstMeta(
        debugName: "storage_usage_bytes",
        argNames: [],
      );

  @override
  Future<CollabCollectionInfo> crateCollabSyncCollabCollection(
      {required String collectionId, required String peerAddr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(collectionId, serializer);
        sse_encode_String(peerAddr, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_collab_collection_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateCollabSyncCollabCollectionConstMeta,
      argValues: [collectionId, peerAddr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateCollabSyncCollabCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "sync_collab_collection",
        argNames: ["collectionId", "peerAddr"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CollabCollectionInfo dco_decode_collab_collection_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CollabCollectionInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      inviteCode: dco_decode_String(arr[2]),
      collaborators: dco_decode_list_collaborator_info(arr[3]),
      media: dco_decode_list_manifest_entry_info(arr[4]),
    );
  }

  @protected
  CollaboratorInfo dco_decode_collaborator_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CollaboratorInfo(
      deviceId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      isAdmin: dco_decode_bool(arr[2]),
    );
  }

  @protected
  DeviceIdentityInfo dco_decode_device_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceIdentityInfo(
      deviceId: dco_decode_String(arr[0]),
      nickname: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<CollabCollectionInfo> dco_decode_list_collab_collection_info(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_collab_collection_info)
        .toList();
  }

  @protected
  List<CollaboratorInfo> dco_decode_list_collaborator_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_collaborator_info).toList();
  }

  @protected
  List<ManifestEntryInfo> dco_decode_list_manifest_entry_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_manifest_entry_info).toList();
  }

  @protected
  List<NewFile> dco_decode_list_new_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_new_file).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TorrentFile> dco_decode_list_torrent_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torrent_file).toList();
  }

  @protected
  List<TorrentInfo> dco_decode_list_torrent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torrent_info).toList();
  }

  @protected
  ManifestEntryInfo dco_decode_manifest_entry_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ManifestEntryInfo(
      infoHash: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      addedBy: dco_decode_String(arr[2]),
      addedAtUnixMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  NewFile dco_decode_new_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NewFile(
      name: dco_decode_String(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  TorrentFile dco_decode_torrent_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TorrentFile(
      name: dco_decode_String(arr[0]),
      absolutePath: dco_decode_String(arr[1]),
      lengthBytes: dco_decode_u_64(arr[2]),
      downloadedBytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  TorrentInfo dco_decode_torrent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return TorrentInfo(
      id: dco_decode_usize(arr[0]),
      infoHash: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      state: dco_decode_String(arr[3]),
      progressBytes: dco_decode_u_64(arr[4]),
      totalBytes: dco_decode_u_64(arr[5]),
      uploadedBytes: dco_decode_u_64(arr[6]),
      downloadMbps: dco_decode_f_64(arr[7]),
      uploadMbps: dco_decode_f_64(arr[8]),
      finished: dco_decode_bool(arr[9]),
      error: dco_decode_opt_String(arr[10]),
      files: dco_decode_list_torrent_file(arr[11]),
      livePeers: dco_decode_u_32(arr[12]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CollabCollectionInfo sse_decode_collab_collection_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_inviteCode = sse_decode_String(deserializer);
    var var_collaborators = sse_decode_list_collaborator_info(deserializer);
    var var_media = sse_decode_list_manifest_entry_info(deserializer);
    return CollabCollectionInfo(
        id: var_id,
        name: var_name,
        inviteCode: var_inviteCode,
        collaborators: var_collaborators,
        media: var_media);
  }

  @protected
  CollaboratorInfo sse_decode_collaborator_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_isAdmin = sse_decode_bool(deserializer);
    return CollaboratorInfo(
        deviceId: var_deviceId,
        displayName: var_displayName,
        isAdmin: var_isAdmin);
  }

  @protected
  DeviceIdentityInfo sse_decode_device_identity_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_nickname = sse_decode_String(deserializer);
    return DeviceIdentityInfo(deviceId: var_deviceId, nickname: var_nickname);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<CollabCollectionInfo> sse_decode_list_collab_collection_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CollabCollectionInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_collab_collection_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<CollaboratorInfo> sse_decode_list_collaborator_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CollaboratorInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_collaborator_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ManifestEntryInfo> sse_decode_list_manifest_entry_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ManifestEntryInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_manifest_entry_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<NewFile> sse_decode_list_new_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NewFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_new_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TorrentFile> sse_decode_list_torrent_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorrentInfo> sse_decode_list_torrent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_info(deserializer));
    }
    return ans_;
  }

  @protected
  ManifestEntryInfo sse_decode_manifest_entry_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_infoHash = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_addedBy = sse_decode_String(deserializer);
    var var_addedAtUnixMs = sse_decode_i_64(deserializer);
    return ManifestEntryInfo(
        infoHash: var_infoHash,
        name: var_name,
        addedBy: var_addedBy,
        addedAtUnixMs: var_addedAtUnixMs);
  }

  @protected
  NewFile sse_decode_new_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return NewFile(name: var_name, bytes: var_bytes);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TorrentFile sse_decode_torrent_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_absolutePath = sse_decode_String(deserializer);
    var var_lengthBytes = sse_decode_u_64(deserializer);
    var var_downloadedBytes = sse_decode_u_64(deserializer);
    return TorrentFile(
        name: var_name,
        absolutePath: var_absolutePath,
        lengthBytes: var_lengthBytes,
        downloadedBytes: var_downloadedBytes);
  }

  @protected
  TorrentInfo sse_decode_torrent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_usize(deserializer);
    var var_infoHash = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_progressBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_uploadedBytes = sse_decode_u_64(deserializer);
    var var_downloadMbps = sse_decode_f_64(deserializer);
    var var_uploadMbps = sse_decode_f_64(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_files = sse_decode_list_torrent_file(deserializer);
    var var_livePeers = sse_decode_u_32(deserializer);
    return TorrentInfo(
        id: var_id,
        infoHash: var_infoHash,
        name: var_name,
        state: var_state,
        progressBytes: var_progressBytes,
        totalBytes: var_totalBytes,
        uploadedBytes: var_uploadedBytes,
        downloadMbps: var_downloadMbps,
        uploadMbps: var_uploadMbps,
        finished: var_finished,
        error: var_error,
        files: var_files,
        livePeers: var_livePeers);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_collab_collection_info(
      CollabCollectionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.inviteCode, serializer);
    sse_encode_list_collaborator_info(self.collaborators, serializer);
    sse_encode_list_manifest_entry_info(self.media, serializer);
  }

  @protected
  void sse_encode_collaborator_info(
      CollaboratorInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.isAdmin, serializer);
  }

  @protected
  void sse_encode_device_identity_info(
      DeviceIdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.nickname, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_collab_collection_info(
      List<CollabCollectionInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_collab_collection_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_collaborator_info(
      List<CollaboratorInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_collaborator_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_manifest_entry_info(
      List<ManifestEntryInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_manifest_entry_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_new_file(List<NewFile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_new_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_torrent_file(
      List<TorrentFile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torrent_info(
      List<TorrentInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_info(item, serializer);
    }
  }

  @protected
  void sse_encode_manifest_entry_info(
      ManifestEntryInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.infoHash, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.addedBy, serializer);
    sse_encode_i_64(self.addedAtUnixMs, serializer);
  }

  @protected
  void sse_encode_new_file(NewFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_torrent_file(TorrentFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.absolutePath, serializer);
    sse_encode_u_64(self.lengthBytes, serializer);
    sse_encode_u_64(self.downloadedBytes, serializer);
  }

  @protected
  void sse_encode_torrent_info(TorrentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.id, serializer);
    sse_encode_String(self.infoHash, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_u_64(self.progressBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.uploadedBytes, serializer);
    sse_encode_f_64(self.downloadMbps, serializer);
    sse_encode_f_64(self.uploadMbps, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_list_torrent_file(self.files, serializer);
    sse_encode_u_32(self.livePeers, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
