// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_info_hash_with_peers`, `bt_listen_port_cached`, `bt_listen_port`, `forget_torrent`, `session_started`, `set_rate_limits`, `storage_breakdown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawStorageEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Create a new collection by seeding local files: write them to disk,
/// build a `.torrent` from them, and add it back to the session pointed at
/// the same location — since the files are already there and match the
/// piece hashes just computed from them, librqbit verifies them as already
/// complete and starts seeding immediately, no download needed. This is
/// the "share something" side of the app; `add_torrent_from_*` above is
/// the "join a swarm" side — both produce the exact same `TorrentInfo`
/// shape either way (see the backend README on why: it's the same
/// protocol regardless of which side of the swarm you started on).
Future<TorrentInfo> createCollection(
        {required String name, required List<NewFile> files}) =>
    RustLib.instance.api.crateTorrentCreateCollection(name: name, files: files);

/// Add a torrent from a magnet link (or bare 40-char info-hash, which
/// `librqbit` also accepts as a magnet-equivalent).
Future<TorrentInfo> addTorrentFromMagnet({required String magnetOrHash}) =>
    RustLib.instance.api
        .crateTorrentAddTorrentFromMagnet(magnetOrHash: magnetOrHash);

/// Add a torrent from the raw bytes of a `.torrent` file (as picked by
/// Flutter's file picker and passed across the FFI boundary).
Future<TorrentInfo> addTorrentFromFileBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateTorrentAddTorrentFromFileBytes(bytes: bytes);

/// Snapshot of every torrent currently managed by the debug session. The
/// Flutter side polls this on a timer — this is a smoke test, not the
/// push-based `watch_*` design the real Collections API will use.
Future<List<TorrentInfo>> listTorrents() =>
    RustLib.instance.api.crateTorrentListTorrents();

/// Where downloaded files actually land, so the UI can show the user a real
/// path instead of leaving them to guess (this was a temp directory before —
/// invisible in practice). A real desktop `MediaStorageSink` (see the
/// backend README) will replace this later; for this smoke test it's just
/// the platform Downloads folder.
Future<String> outputDir() => RustLib.instance.api.crateTorrentOutputDir();

/// Real disk usage of everything downloaded/shared so far — the Settings
/// screen's storage meter. Recursive over `output_dir()`.
Future<BigInt> storageUsageBytes() =>
    RustLib.instance.api.crateTorrentStorageUsageBytes();

/// One file to seed, as picked by Flutter (camera roll, file picker, etc.)
/// and passed across the FFI boundary as raw bytes — the only form that's
/// meaningfully the same file on every platform (mobile file pickers often
/// hand back a cache copy path, not a stable one worth trusting).
class NewFile {
  final String name;
  final Uint8List bytes;

  const NewFile({
    required this.name,
    required this.bytes,
  });

  @override
  int get hashCode => name.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bytes == other.bytes;
}

/// One file inside a torrent, with its real on-disk location — resolved via
/// `librqbit::Api` (which knows the actual per-torrent output folder,
/// including the subfolder it auto-creates for multi-file torrents) rather
/// than guessed, so Flutter can load a thumbnail or open/play it directly.
class TorrentFile {
  final String name;
  final String absolutePath;
  final BigInt lengthBytes;
  final BigInt downloadedBytes;

  const TorrentFile({
    required this.name,
    required this.absolutePath,
    required this.lengthBytes,
    required this.downloadedBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      absolutePath.hashCode ^
      lengthBytes.hashCode ^
      downloadedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          absolutePath == other.absolutePath &&
          lengthBytes == other.lengthBytes &&
          downloadedBytes == other.downloadedBytes;
}

class TorrentInfo {
  final BigInt id;
  final String infoHash;
  final String name;
  final String state;
  final BigInt progressBytes;
  final BigInt totalBytes;
  final BigInt uploadedBytes;
  final double downloadMbps;
  final double uploadMbps;
  final bool finished;
  final String? error;
  final List<TorrentFile> files;

  /// Currently-connected peers (not the historical total ever seen) — the
  /// closest real equivalent to the mockup's "N copies alive" indicator.
  final int livePeers;

  const TorrentInfo({
    required this.id,
    required this.infoHash,
    required this.name,
    required this.state,
    required this.progressBytes,
    required this.totalBytes,
    required this.uploadedBytes,
    required this.downloadMbps,
    required this.uploadMbps,
    required this.finished,
    this.error,
    required this.files,
    required this.livePeers,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      infoHash.hashCode ^
      name.hashCode ^
      state.hashCode ^
      progressBytes.hashCode ^
      totalBytes.hashCode ^
      uploadedBytes.hashCode ^
      downloadMbps.hashCode ^
      uploadMbps.hashCode ^
      finished.hashCode ^
      error.hashCode ^
      files.hashCode ^
      livePeers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          infoHash == other.infoHash &&
          name == other.name &&
          state == other.state &&
          progressBytes == other.progressBytes &&
          totalBytes == other.totalBytes &&
          uploadedBytes == other.uploadedBytes &&
          downloadMbps == other.downloadMbps &&
          uploadMbps == other.uploadMbps &&
          finished == other.finished &&
          error == other.error &&
          files == other.files &&
          livePeers == other.livePeers;
}
