import Cocoa
import FlutterMacOS

/// The size the app opens at, and the smallest it can be dragged to.
///
/// `RootShell` chooses its layout on available width alone — at or above
/// `kDesktopBreakpoint` (1000pt, see lib/screens/root_shell.dart) it renders
/// the three-pane desktop shell, and below that the phone layout. The stock
/// runner opened at 800x600, so the Mac app launched into the phone layout
/// every time and had to be widened by hand. Opening well clear of the
/// breakpoint fixes that.
///
/// The minimum deliberately sits *below* the breakpoint: the phone layout is
/// a first-class layout here, not a fallback, and it is the right rendering
/// for a narrow window parked beside something else. 375x667 is the smallest
/// phone the design targets, so nothing between the minimum and the
/// breakpoint is untested territory.
private let kDefaultWindowSize = NSSize(width: 1280, height: 840)
private let kMinimumWindowSize = NSSize(width: 375, height: 667)

class MainFlutterWindow: NSWindow {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController()
    self.contentViewController = flutterViewController

    // Set alongside the nib's own frame rather than instead of it: the nib
    // decides what is on screen for the first frame, this keeps the number
    // correct if the nib is ever regenerated by `flutter create`.
    self.contentMinSize = kMinimumWindowSize
    self.setContentSize(kDefaultWindowSize)
    self.center()

    RegisterGeneratedPlugins(registry: flutterViewController)
    HeicPreview().register(with: flutterViewController.engine.binaryMessenger)

    super.awakeFromNib()
  }
}
