// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'nexus/device.dart';
import 'nexus/settings.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'portalis_api.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AppSnapshot> dco_decode_StreamSink_app_snapshot_Sse(
      dynamic raw);

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
      dynamic raw);

  @protected
  RustStreamSink<AppDetail?>
      dco_decode_StreamSink_opt_box_autoadd_app_detail_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppAccepted dco_decode_app_accepted(dynamic raw);

  @protected
  AppCollection dco_decode_app_collection(dynamic raw);

  @protected
  AppCollectionPeer dco_decode_app_collection_peer(dynamic raw);

  @protected
  AppCommand dco_decode_app_command(dynamic raw);

  @protected
  AppContact dco_decode_app_contact(dynamic raw);

  @protected
  AppDetail dco_decode_app_detail(dynamic raw);

  @protected
  AppDevice dco_decode_app_device(dynamic raw);

  @protected
  AppEntry dco_decode_app_entry(dynamic raw);

  @protected
  AppPeer dco_decode_app_peer(dynamic raw);

  @protected
  AppPeerHistory dco_decode_app_peer_history(dynamic raw);

  @protected
  AppPending dco_decode_app_pending(dynamic raw);

  @protected
  AppPeoplePeer dco_decode_app_people_peer(dynamic raw);

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw);

  @protected
  AppSourceFile dco_decode_app_source_file(dynamic raw);

  @protected
  AppStorageEntry dco_decode_app_storage_entry(dynamic raw);

  @protected
  AppTransfer dco_decode_app_transfer(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppCommand dco_decode_box_autoadd_app_command(dynamic raw);

  @protected
  AppDetail dco_decode_box_autoadd_app_detail(dynamic raw);

  @protected
  AppPending dco_decode_box_autoadd_app_pending(dynamic raw);

  @protected
  AppTransfer dco_decode_box_autoadd_app_transfer(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  EngineSettings dco_decode_box_autoadd_engine_settings(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DeviceIdentityInfo dco_decode_device_identity_info(dynamic raw);

  @protected
  EngineSettings dco_decode_engine_settings(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AppCollection> dco_decode_list_app_collection(dynamic raw);

  @protected
  List<AppCollectionPeer> dco_decode_list_app_collection_peer(dynamic raw);

  @protected
  List<AppContact> dco_decode_list_app_contact(dynamic raw);

  @protected
  List<AppEntry> dco_decode_list_app_entry(dynamic raw);

  @protected
  List<AppPeer> dco_decode_list_app_peer(dynamic raw);

  @protected
  List<AppPeerHistory> dco_decode_list_app_peer_history(dynamic raw);

  @protected
  List<AppPeoplePeer> dco_decode_list_app_people_peer(dynamic raw);

  @protected
  List<AppSourceFile> dco_decode_list_app_source_file(dynamic raw);

  @protected
  List<AppStorageEntry> dco_decode_list_app_storage_entry(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppDetail? dco_decode_opt_box_autoadd_app_detail(dynamic raw);

  @protected
  AppPending? dco_decode_opt_box_autoadd_app_pending(dynamic raw);

  @protected
  AppTransfer? dco_decode_opt_box_autoadd_app_transfer(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AppSnapshot> sse_decode_StreamSink_app_snapshot_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<AppDetail?>
      sse_decode_StreamSink_opt_box_autoadd_app_detail_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppAccepted sse_decode_app_accepted(SseDeserializer deserializer);

  @protected
  AppCollection sse_decode_app_collection(SseDeserializer deserializer);

  @protected
  AppCollectionPeer sse_decode_app_collection_peer(
      SseDeserializer deserializer);

  @protected
  AppCommand sse_decode_app_command(SseDeserializer deserializer);

  @protected
  AppContact sse_decode_app_contact(SseDeserializer deserializer);

  @protected
  AppDetail sse_decode_app_detail(SseDeserializer deserializer);

  @protected
  AppDevice sse_decode_app_device(SseDeserializer deserializer);

  @protected
  AppEntry sse_decode_app_entry(SseDeserializer deserializer);

  @protected
  AppPeer sse_decode_app_peer(SseDeserializer deserializer);

  @protected
  AppPeerHistory sse_decode_app_peer_history(SseDeserializer deserializer);

  @protected
  AppPending sse_decode_app_pending(SseDeserializer deserializer);

  @protected
  AppPeoplePeer sse_decode_app_people_peer(SseDeserializer deserializer);

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer);

  @protected
  AppSourceFile sse_decode_app_source_file(SseDeserializer deserializer);

  @protected
  AppStorageEntry sse_decode_app_storage_entry(SseDeserializer deserializer);

  @protected
  AppTransfer sse_decode_app_transfer(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppCommand sse_decode_box_autoadd_app_command(SseDeserializer deserializer);

  @protected
  AppDetail sse_decode_box_autoadd_app_detail(SseDeserializer deserializer);

  @protected
  AppPending sse_decode_box_autoadd_app_pending(SseDeserializer deserializer);

  @protected
  AppTransfer sse_decode_box_autoadd_app_transfer(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EngineSettings sse_decode_box_autoadd_engine_settings(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DeviceIdentityInfo sse_decode_device_identity_info(
      SseDeserializer deserializer);

  @protected
  EngineSettings sse_decode_engine_settings(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AppCollection> sse_decode_list_app_collection(
      SseDeserializer deserializer);

  @protected
  List<AppCollectionPeer> sse_decode_list_app_collection_peer(
      SseDeserializer deserializer);

  @protected
  List<AppContact> sse_decode_list_app_contact(SseDeserializer deserializer);

  @protected
  List<AppEntry> sse_decode_list_app_entry(SseDeserializer deserializer);

  @protected
  List<AppPeer> sse_decode_list_app_peer(SseDeserializer deserializer);

  @protected
  List<AppPeerHistory> sse_decode_list_app_peer_history(
      SseDeserializer deserializer);

  @protected
  List<AppPeoplePeer> sse_decode_list_app_people_peer(
      SseDeserializer deserializer);

  @protected
  List<AppSourceFile> sse_decode_list_app_source_file(
      SseDeserializer deserializer);

  @protected
  List<AppStorageEntry> sse_decode_list_app_storage_entry(
      SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppDetail? sse_decode_opt_box_autoadd_app_detail(
      SseDeserializer deserializer);

  @protected
  AppPending? sse_decode_opt_box_autoadd_app_pending(
      SseDeserializer deserializer);

  @protected
  AppTransfer? sse_decode_opt_box_autoadd_app_transfer(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_app_snapshot_Sse(
      RustStreamSink<AppSnapshot> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
      RustStreamSink<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_app_detail_Sse(
      RustStreamSink<AppDetail?> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_accepted(AppAccepted self, SseSerializer serializer);

  @protected
  void sse_encode_app_collection(AppCollection self, SseSerializer serializer);

  @protected
  void sse_encode_app_collection_peer(
      AppCollectionPeer self, SseSerializer serializer);

  @protected
  void sse_encode_app_command(AppCommand self, SseSerializer serializer);

  @protected
  void sse_encode_app_contact(AppContact self, SseSerializer serializer);

  @protected
  void sse_encode_app_detail(AppDetail self, SseSerializer serializer);

  @protected
  void sse_encode_app_device(AppDevice self, SseSerializer serializer);

  @protected
  void sse_encode_app_entry(AppEntry self, SseSerializer serializer);

  @protected
  void sse_encode_app_peer(AppPeer self, SseSerializer serializer);

  @protected
  void sse_encode_app_peer_history(
      AppPeerHistory self, SseSerializer serializer);

  @protected
  void sse_encode_app_pending(AppPending self, SseSerializer serializer);

  @protected
  void sse_encode_app_people_peer(AppPeoplePeer self, SseSerializer serializer);

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_app_source_file(AppSourceFile self, SseSerializer serializer);

  @protected
  void sse_encode_app_storage_entry(
      AppStorageEntry self, SseSerializer serializer);

  @protected
  void sse_encode_app_transfer(AppTransfer self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_command(
      AppCommand self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_detail(
      AppDetail self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_pending(
      AppPending self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_transfer(
      AppTransfer self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_engine_settings(
      EngineSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_device_identity_info(
      DeviceIdentityInfo self, SseSerializer serializer);

  @protected
  void sse_encode_engine_settings(
      EngineSettings self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_collection(
      List<AppCollection> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_collection_peer(
      List<AppCollectionPeer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_contact(
      List<AppContact> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_entry(List<AppEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_peer(List<AppPeer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_peer_history(
      List<AppPeerHistory> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_people_peer(
      List<AppPeoplePeer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_source_file(
      List<AppSourceFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_storage_entry(
      List<AppStorageEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_detail(
      AppDetail? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_pending(
      AppPending? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_transfer(
      AppTransfer? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
