// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'device.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'nexus_settings.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'portalis_api.dart';
import 'settings.dart';
import 'torrent.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1225709876;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'backend',
    ioDirectory: 'rust/backend/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<TorrentInfo> crateTorrentAddTorrentFromFilePath(
      {required String path});

  Future<TorrentInfo> crateTorrentAddTorrentFromMagnet(
      {required String magnetOrHash});

  Future<TorrentInfo> crateTorrentCreateCollection(
      {required String name, required List<SourceFile> files});

  Future<EngineSettings> crateSettingsDefaultEngineSettings();

  Future<DeviceIdentityInfo> crateDeviceDeviceIdentity();

  Future<EngineSettings> crateSettingsEngineSettings();

  Future<EngineSettings> crateSettingsEngineSettingsDefault();

  String crateBridgeGetVersion();

  Future<List<TorrentInfo>> crateTorrentListTorrents();

  Future<NexusEndpointConfig> crateNexusSettingsNexusEndpointConfig();

  Future<NexusEndpointConfig> crateNexusSettingsNexusEndpointConfigDefault();

  Future<String> crateTorrentOutputDir();

  Future<AppAccepted> cratePortalisApiSend({required AppCommand command});

  Future<void> cratePortalisApiSetActive({required bool active});

  Future<bool> crateSettingsSetEngineSettings(
      {required EngineSettings settings});

  Future<void> crateNexusSettingsSetNexusEndpointConfig(
      {required NexusEndpointConfig config});

  Future<DeviceIdentityInfo> crateDeviceSetNickname({required String nickname});

  Future<void> cratePortalisApiStart();

  Future<void> cratePortalisApiStop();

  Future<List<AppStorageEntry>> cratePortalisApiStorageBreakdown();

  Future<BigInt> crateTorrentStorageUsageBytes();

  Future<bool> crateTorrentTorrentInfoKnowsProgress(
      {required TorrentInfo that});

  Stream<AppDetail?> cratePortalisApiWatchDetail({int? collection});

  Stream<AppSnapshot> cratePortalisApiWatchStates();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<TorrentInfo> crateTorrentAddTorrentFromFilePath(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentAddTorrentFromFilePathConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentAddTorrentFromFilePathConstMeta =>
      const TaskConstMeta(
        debugName: "add_torrent_from_file_path",
        argNames: ["path"],
      );

  @override
  Future<TorrentInfo> crateTorrentAddTorrentFromMagnet(
      {required String magnetOrHash}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(magnetOrHash, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentAddTorrentFromMagnetConstMeta,
      argValues: [magnetOrHash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentAddTorrentFromMagnetConstMeta =>
      const TaskConstMeta(
        debugName: "add_torrent_from_magnet",
        argNames: ["magnetOrHash"],
      );

  @override
  Future<TorrentInfo> crateTorrentCreateCollection(
      {required String name, required List<SourceFile> files}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_list_source_file(files, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentCreateCollectionConstMeta,
      argValues: [name, files],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentCreateCollectionConstMeta =>
      const TaskConstMeta(
        debugName: "create_collection",
        argNames: ["name", "files"],
      );

  @override
  Future<EngineSettings> crateSettingsDefaultEngineSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_engine_settings,
        decodeErrorData: null,
      ),
      constMeta: kCrateSettingsDefaultEngineSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateSettingsDefaultEngineSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "default_engine_settings",
        argNames: [],
      );

  @override
  Future<DeviceIdentityInfo> crateDeviceDeviceIdentity() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_device_identity_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateDeviceDeviceIdentityConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateDeviceDeviceIdentityConstMeta => const TaskConstMeta(
        debugName: "device_identity",
        argNames: [],
      );

  @override
  Future<EngineSettings> crateSettingsEngineSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_engine_settings,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateSettingsEngineSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateSettingsEngineSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "engine_settings",
        argNames: [],
      );

  @override
  Future<EngineSettings> crateSettingsEngineSettingsDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_engine_settings,
        decodeErrorData: null,
      ),
      constMeta: kCrateSettingsEngineSettingsDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateSettingsEngineSettingsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "engine_settings_default",
        argNames: [],
      );

  @override
  String crateBridgeGetVersion() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateBridgeGetVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeGetVersionConstMeta => const TaskConstMeta(
        debugName: "get_version",
        argNames: [],
      );

  @override
  Future<List<TorrentInfo>> crateTorrentListTorrents() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_torrent_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentListTorrentsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentListTorrentsConstMeta => const TaskConstMeta(
        debugName: "list_torrents",
        argNames: [],
      );

  @override
  Future<NexusEndpointConfig> crateNexusSettingsNexusEndpointConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_nexus_endpoint_config,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateNexusSettingsNexusEndpointConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateNexusSettingsNexusEndpointConfigConstMeta =>
      const TaskConstMeta(
        debugName: "nexus_endpoint_config",
        argNames: [],
      );

  @override
  Future<NexusEndpointConfig> crateNexusSettingsNexusEndpointConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_nexus_endpoint_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateNexusSettingsNexusEndpointConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateNexusSettingsNexusEndpointConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "nexus_endpoint_config_default",
        argNames: [],
      );

  @override
  Future<String> crateTorrentOutputDir() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentOutputDirConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentOutputDirConstMeta => const TaskConstMeta(
        debugName: "output_dir",
        argNames: [],
      );

  @override
  Future<AppAccepted> cratePortalisApiSend({required AppCommand command}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_app_command(command, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_app_accepted,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiSendConstMeta,
      argValues: [command],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCratePortalisApiSendConstMeta => const TaskConstMeta(
        debugName: "send",
        argNames: ["command"],
      );

  @override
  Future<void> cratePortalisApiSetActive({required bool active}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(active, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiSetActiveConstMeta,
      argValues: [active],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCratePortalisApiSetActiveConstMeta => const TaskConstMeta(
        debugName: "set_active",
        argNames: ["active"],
      );

  @override
  Future<bool> crateSettingsSetEngineSettings(
      {required EngineSettings settings}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_engine_settings(settings, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateSettingsSetEngineSettingsConstMeta,
      argValues: [settings],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateSettingsSetEngineSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "set_engine_settings",
        argNames: ["settings"],
      );

  @override
  Future<void> crateNexusSettingsSetNexusEndpointConfig(
      {required NexusEndpointConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_nexus_endpoint_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateNexusSettingsSetNexusEndpointConfigConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateNexusSettingsSetNexusEndpointConfigConstMeta =>
      const TaskConstMeta(
        debugName: "set_nexus_endpoint_config",
        argNames: ["config"],
      );

  @override
  Future<DeviceIdentityInfo> crateDeviceSetNickname(
      {required String nickname}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nickname, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_device_identity_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateDeviceSetNicknameConstMeta,
      argValues: [nickname],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateDeviceSetNicknameConstMeta => const TaskConstMeta(
        debugName: "set_nickname",
        argNames: ["nickname"],
      );

  @override
  Future<void> cratePortalisApiStart() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiStartConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCratePortalisApiStartConstMeta => const TaskConstMeta(
        debugName: "start",
        argNames: [],
      );

  @override
  Future<void> cratePortalisApiStop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiStopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCratePortalisApiStopConstMeta => const TaskConstMeta(
        debugName: "stop",
        argNames: [],
      );

  @override
  Future<List<AppStorageEntry>> cratePortalisApiStorageBreakdown() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_app_storage_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiStorageBreakdownConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCratePortalisApiStorageBreakdownConstMeta =>
      const TaskConstMeta(
        debugName: "storage_breakdown",
        argNames: [],
      );

  @override
  Future<BigInt> crateTorrentStorageUsageBytes() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateTorrentStorageUsageBytesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentStorageUsageBytesConstMeta =>
      const TaskConstMeta(
        debugName: "storage_usage_bytes",
        argNames: [],
      );

  @override
  Future<bool> crateTorrentTorrentInfoKnowsProgress(
      {required TorrentInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_torrent_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateTorrentTorrentInfoKnowsProgressConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateTorrentTorrentInfoKnowsProgressConstMeta =>
      const TaskConstMeta(
        debugName: "torrent_info_knows_progress",
        argNames: ["that"],
      );

  @override
  Stream<AppDetail?> cratePortalisApiWatchDetail({int? collection}) {
    final sink = RustStreamSink<AppDetail?>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_box_autoadd_u_32(collection, serializer);
        sse_encode_StreamSink_opt_box_autoadd_app_detail_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiWatchDetailConstMeta,
      argValues: [collection, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCratePortalisApiWatchDetailConstMeta =>
      const TaskConstMeta(
        debugName: "watch_detail",
        argNames: ["collection", "sink"],
      );

  @override
  Stream<AppSnapshot> cratePortalisApiWatchStates() {
    final sink = RustStreamSink<AppSnapshot>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_app_snapshot_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCratePortalisApiWatchStatesConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCratePortalisApiWatchStatesConstMeta =>
      const TaskConstMeta(
        debugName: "watch_states",
        argNames: ["sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AppSnapshot> dco_decode_StreamSink_app_snapshot_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<AppDetail?>
      dco_decode_StreamSink_opt_box_autoadd_app_detail_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppAccepted dco_decode_app_accepted(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AppAccepted(
      id: dco_decode_u_64(arr[0]),
      collection: dco_decode_opt_box_autoadd_u_32(arr[1]),
      queued: dco_decode_bool(arr[2]),
    );
  }

  @protected
  AppCollection dco_decode_app_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return AppCollection(
      id: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      nature: dco_decode_String(arr[2]),
      role: dco_decode_String(arr[3]),
      revision: dco_decode_u_64(arr[4]),
      status: dco_decode_String(arr[5]),
      members: dco_decode_list_prim_u_32_strict(arr[6]),
      entries: dco_decode_u_32(arr[7]),
      totalBytes: dco_decode_u_64(arr[8]),
      onDiskBytes: dco_decode_u_64(arr[9]),
      uploadedBytes: dco_decode_u_64(arr[10]),
      startedAt: dco_decode_opt_box_autoadd_u_64(arr[11]),
      completedAt: dco_decode_opt_box_autoadd_u_64(arr[12]),
      transfer: dco_decode_opt_box_autoadd_app_transfer(arr[13]),
      pending: dco_decode_opt_box_autoadd_app_pending(arr[14]),
    );
  }

  @protected
  AppCommand dco_decode_app_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return AppCommand(
      kind: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      files: dco_decode_list_app_source_file(arr[2]),
      collection: dco_decode_opt_box_autoadd_u_32(arr[3]),
      label: dco_decode_opt_String(arr[4]),
      deleteFiles: dco_decode_opt_box_autoadd_bool(arr[5]),
      entry: dco_decode_opt_box_autoadd_u_32(arr[6]),
      source: dco_decode_opt_String(arr[7]),
      entries: dco_decode_list_prim_u_32_strict(arr[8]),
      contact: dco_decode_opt_box_autoadd_u_32(arr[9]),
      handle: dco_decode_opt_String(arr[10]),
      accept: dco_decode_opt_box_autoadd_bool(arr[11]),
      device: dco_decode_opt_box_autoadd_u_32(arr[12]),
      active: dco_decode_opt_box_autoadd_bool(arr[13]),
      paused: dco_decode_opt_box_autoadd_bool(arr[14]),
    );
  }

  @protected
  AppContact dco_decode_app_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AppContact(
      id: dco_decode_u_32(arr[0]),
      displayName: dco_decode_String(arr[1]),
      handle: dco_decode_opt_String(arr[2]),
      fingerprint: dco_decode_String(arr[3]),
      verified: dco_decode_bool(arr[4]),
      friendship: dco_decode_String(arr[5]),
      reachable: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  AppDetail dco_decode_app_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppDetail(
      id: dco_decode_u_32(arr[0]),
      entries: dco_decode_list_app_entry(arr[1]),
      pieces: dco_decode_list_prim_u_8_strict(arr[2]),
      samples: dco_decode_list_prim_u_8_strict(arr[3]),
      peers: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  AppDevice dco_decode_app_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppDevice(
      name: dco_decode_String(arr[0]),
      handle: dco_decode_opt_String(arr[1]),
      fingerprint: dco_decode_String(arr[2]),
      devices: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  AppEntry dco_decode_app_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AppEntry(
      id: dco_decode_u_32(arr[0]),
      label: dco_decode_String(arr[1]),
      bytes: dco_decode_u_64(arr[2]),
      selected: dco_decode_bool(arr[3]),
      available: dco_decode_bool(arr[4]),
      downloadedBytes: dco_decode_u_64(arr[5]),
      path: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  AppPending dco_decode_app_pending(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AppPending(
      command: dco_decode_u_64(arr[0]),
      queued: dco_decode_bool(arr[1]),
    );
  }

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppSnapshot(
      device: dco_decode_app_device(arr[0]),
      connectivity: dco_decode_String(arr[1]),
      contacts: dco_decode_list_app_contact(arr[2]),
      collections: dco_decode_list_app_collection(arr[3]),
      alerts: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  AppSourceFile dco_decode_app_source_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AppSourceFile(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      bytes: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  AppStorageEntry dco_decode_app_storage_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppStorageEntry(
      name: dco_decode_String(arr[0]),
      bytes: dco_decode_u_64(arr[1]),
      path: dco_decode_String(arr[2]),
      collection: dco_decode_opt_box_autoadd_u_32(arr[3]),
      collectionName: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  AppTransfer dco_decode_app_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppTransfer(
      progress: dco_decode_f_32(arr[0]),
      downBytesPerSecond: dco_decode_u_32(arr[1]),
      upBytesPerSecond: dco_decode_u_32(arr[2]),
      peers: dco_decode_u_16(arr[3]),
      etaSecs: dco_decode_opt_box_autoadd_u_32(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppCommand dco_decode_box_autoadd_app_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_command(raw);
  }

  @protected
  AppDetail dco_decode_box_autoadd_app_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_detail(raw);
  }

  @protected
  AppPending dco_decode_box_autoadd_app_pending(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_pending(raw);
  }

  @protected
  AppTransfer dco_decode_box_autoadd_app_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_transfer(raw);
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EngineSettings dco_decode_box_autoadd_engine_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_engine_settings(raw);
  }

  @protected
  NexusEndpointConfig dco_decode_box_autoadd_nexus_endpoint_config(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_nexus_endpoint_config(raw);
  }

  @protected
  TorrentInfo dco_decode_box_autoadd_torrent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_torrent_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DeviceIdentityInfo dco_decode_device_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceIdentityInfo(
      deviceId: dco_decode_String(arr[0]),
      nickname: dco_decode_String(arr[1]),
    );
  }

  @protected
  EngineSettings dco_decode_engine_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return EngineSettings(
      uploadLimitBps: dco_decode_opt_box_autoadd_u_32(arr[0]),
      downloadLimitBps: dco_decode_opt_box_autoadd_u_32(arr[1]),
      downloadDir: dco_decode_opt_String(arr[2]),
      listenPortStart: dco_decode_u_16(arr[3]),
      listenPortEnd: dco_decode_u_16(arr[4]),
      enableUpnpPortForwarding: dco_decode_bool(arr[5]),
      socksProxyUrl: dco_decode_opt_String(arr[6]),
      disableDht: dco_decode_bool(arr[7]),
      disableDhtPersistence: dco_decode_bool(arr[8]),
      persistSession: dco_decode_bool(arr[9]),
      fastresume: dco_decode_bool(arr[10]),
      deferWritesUpToMb: dco_decode_opt_box_autoadd_u_32(arr[11]),
      concurrentInitLimit: dco_decode_opt_box_autoadd_u_32(arr[12]),
      peerConnectTimeoutSecs: dco_decode_opt_box_autoadd_u_32(arr[13]),
      peerReadWriteTimeoutSecs: dco_decode_opt_box_autoadd_u_32(arr[14]),
      peerKeepAliveIntervalSecs: dco_decode_opt_box_autoadd_u_32(arr[15]),
      blocklistUrl: dco_decode_opt_String(arr[16]),
      trackers: dco_decode_list_String(arr[17]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AppCollection> dco_decode_list_app_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_collection).toList();
  }

  @protected
  List<AppContact> dco_decode_list_app_contact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_contact).toList();
  }

  @protected
  List<AppEntry> dco_decode_list_app_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_entry).toList();
  }

  @protected
  List<AppSourceFile> dco_decode_list_app_source_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_source_file).toList();
  }

  @protected
  List<AppStorageEntry> dco_decode_list_app_storage_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_storage_entry).toList();
  }

  @protected
  List<PieceRun> dco_decode_list_piece_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_piece_run).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SourceFile> dco_decode_list_source_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_source_file).toList();
  }

  @protected
  List<TorrentFile> dco_decode_list_torrent_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torrent_file).toList();
  }

  @protected
  List<TorrentInfo> dco_decode_list_torrent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torrent_info).toList();
  }

  @protected
  NexusEndpointConfig dco_decode_nexus_endpoint_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NexusEndpointConfig(
      nodeId: dco_decode_opt_String(arr[0]),
      directAddress: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AppDetail? dco_decode_opt_box_autoadd_app_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_app_detail(raw);
  }

  @protected
  AppPending? dco_decode_opt_box_autoadd_app_pending(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_app_pending(raw);
  }

  @protected
  AppTransfer? dco_decode_opt_box_autoadd_app_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_app_transfer(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PieceRun dco_decode_piece_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PieceRun(
      offsetBytes: dco_decode_u_64(arr[0]),
      lengthBytes: dco_decode_u_64(arr[1]),
      verified: dco_decode_bool(arr[2]),
      peers: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  SourceFile dco_decode_source_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SourceFile(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      lengthBytes: dco_decode_opt_box_autoadd_u_64(arr[2]),
    );
  }

  @protected
  TorrentFile dco_decode_torrent_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TorrentFile(
      name: dco_decode_String(arr[0]),
      absolutePath: dco_decode_String(arr[1]),
      lengthBytes: dco_decode_u_64(arr[2]),
      downloadedBytes: dco_decode_u_64(arr[3]),
      pieceRuns: dco_decode_list_piece_run(arr[4]),
    );
  }

  @protected
  TorrentInfo dco_decode_torrent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return TorrentInfo(
      id: dco_decode_usize(arr[0]),
      infoHash: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      state: dco_decode_String(arr[3]),
      progressBytes: dco_decode_u_64(arr[4]),
      totalBytes: dco_decode_u_64(arr[5]),
      uploadedBytes: dco_decode_u_64(arr[6]),
      downloadMbps: dco_decode_f_64(arr[7]),
      uploadMbps: dco_decode_f_64(arr[8]),
      finished: dco_decode_bool(arr[9]),
      error: dco_decode_opt_String(arr[10]),
      files: dco_decode_list_torrent_file(arr[11]),
      livePeers: dco_decode_u_32(arr[12]),
      livePeerAddrs: dco_decode_list_String(arr[13]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AppSnapshot> sse_decode_StreamSink_app_snapshot_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<AppDetail?>
      sse_decode_StreamSink_opt_box_autoadd_app_detail_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppAccepted sse_decode_app_accepted(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_collection = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_queued = sse_decode_bool(deserializer);
    return AppAccepted(
        id: var_id, collection: var_collection, queued: var_queued);
  }

  @protected
  AppCollection sse_decode_app_collection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_nature = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_revision = sse_decode_u_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_members = sse_decode_list_prim_u_32_strict(deserializer);
    var var_entries = sse_decode_u_32(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_onDiskBytes = sse_decode_u_64(deserializer);
    var var_uploadedBytes = sse_decode_u_64(deserializer);
    var var_startedAt = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_completedAt = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_transfer = sse_decode_opt_box_autoadd_app_transfer(deserializer);
    var var_pending = sse_decode_opt_box_autoadd_app_pending(deserializer);
    return AppCollection(
        id: var_id,
        name: var_name,
        nature: var_nature,
        role: var_role,
        revision: var_revision,
        status: var_status,
        members: var_members,
        entries: var_entries,
        totalBytes: var_totalBytes,
        onDiskBytes: var_onDiskBytes,
        uploadedBytes: var_uploadedBytes,
        startedAt: var_startedAt,
        completedAt: var_completedAt,
        transfer: var_transfer,
        pending: var_pending);
  }

  @protected
  AppCommand sse_decode_app_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_files = sse_decode_list_app_source_file(deserializer);
    var var_collection = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    var var_deleteFiles = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_entry = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_source = sse_decode_opt_String(deserializer);
    var var_entries = sse_decode_list_prim_u_32_strict(deserializer);
    var var_contact = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_handle = sse_decode_opt_String(deserializer);
    var var_accept = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_device = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_active = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_paused = sse_decode_opt_box_autoadd_bool(deserializer);
    return AppCommand(
        kind: var_kind,
        name: var_name,
        files: var_files,
        collection: var_collection,
        label: var_label,
        deleteFiles: var_deleteFiles,
        entry: var_entry,
        source: var_source,
        entries: var_entries,
        contact: var_contact,
        handle: var_handle,
        accept: var_accept,
        device: var_device,
        active: var_active,
        paused: var_paused);
  }

  @protected
  AppContact sse_decode_app_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_handle = sse_decode_opt_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    var var_friendship = sse_decode_String(deserializer);
    var var_reachable = sse_decode_opt_String(deserializer);
    return AppContact(
        id: var_id,
        displayName: var_displayName,
        handle: var_handle,
        fingerprint: var_fingerprint,
        verified: var_verified,
        friendship: var_friendship,
        reachable: var_reachable);
  }

  @protected
  AppDetail sse_decode_app_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_entries = sse_decode_list_app_entry(deserializer);
    var var_pieces = sse_decode_list_prim_u_8_strict(deserializer);
    var var_samples = sse_decode_list_prim_u_8_strict(deserializer);
    var var_peers = sse_decode_list_String(deserializer);
    return AppDetail(
        id: var_id,
        entries: var_entries,
        pieces: var_pieces,
        samples: var_samples,
        peers: var_peers);
  }

  @protected
  AppDevice sse_decode_app_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_handle = sse_decode_opt_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    var var_devices = sse_decode_u_32(deserializer);
    return AppDevice(
        name: var_name,
        handle: var_handle,
        fingerprint: var_fingerprint,
        devices: var_devices);
  }

  @protected
  AppEntry sse_decode_app_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    var var_selected = sse_decode_bool(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_downloadedBytes = sse_decode_u_64(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    return AppEntry(
        id: var_id,
        label: var_label,
        bytes: var_bytes,
        selected: var_selected,
        available: var_available,
        downloadedBytes: var_downloadedBytes,
        path: var_path);
  }

  @protected
  AppPending sse_decode_app_pending(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_command = sse_decode_u_64(deserializer);
    var var_queued = sse_decode_bool(deserializer);
    return AppPending(command: var_command, queued: var_queued);
  }

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_device = sse_decode_app_device(deserializer);
    var var_connectivity = sse_decode_String(deserializer);
    var var_contacts = sse_decode_list_app_contact(deserializer);
    var var_collections = sse_decode_list_app_collection(deserializer);
    var var_alerts = sse_decode_list_String(deserializer);
    return AppSnapshot(
        device: var_device,
        connectivity: var_connectivity,
        contacts: var_contacts,
        collections: var_collections,
        alerts: var_alerts);
  }

  @protected
  AppSourceFile sse_decode_app_source_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    return AppSourceFile(name: var_name, path: var_path, bytes: var_bytes);
  }

  @protected
  AppStorageEntry sse_decode_app_storage_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_collection = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_collectionName = sse_decode_opt_String(deserializer);
    return AppStorageEntry(
        name: var_name,
        bytes: var_bytes,
        path: var_path,
        collection: var_collection,
        collectionName: var_collectionName);
  }

  @protected
  AppTransfer sse_decode_app_transfer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_32(deserializer);
    var var_downBytesPerSecond = sse_decode_u_32(deserializer);
    var var_upBytesPerSecond = sse_decode_u_32(deserializer);
    var var_peers = sse_decode_u_16(deserializer);
    var var_etaSecs = sse_decode_opt_box_autoadd_u_32(deserializer);
    return AppTransfer(
        progress: var_progress,
        downBytesPerSecond: var_downBytesPerSecond,
        upBytesPerSecond: var_upBytesPerSecond,
        peers: var_peers,
        etaSecs: var_etaSecs);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppCommand sse_decode_box_autoadd_app_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_command(deserializer));
  }

  @protected
  AppDetail sse_decode_box_autoadd_app_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_detail(deserializer));
  }

  @protected
  AppPending sse_decode_box_autoadd_app_pending(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_pending(deserializer));
  }

  @protected
  AppTransfer sse_decode_box_autoadd_app_transfer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_transfer(deserializer));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  EngineSettings sse_decode_box_autoadd_engine_settings(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_engine_settings(deserializer));
  }

  @protected
  NexusEndpointConfig sse_decode_box_autoadd_nexus_endpoint_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_nexus_endpoint_config(deserializer));
  }

  @protected
  TorrentInfo sse_decode_box_autoadd_torrent_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_torrent_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DeviceIdentityInfo sse_decode_device_identity_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_nickname = sse_decode_String(deserializer);
    return DeviceIdentityInfo(deviceId: var_deviceId, nickname: var_nickname);
  }

  @protected
  EngineSettings sse_decode_engine_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uploadLimitBps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_downloadLimitBps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_downloadDir = sse_decode_opt_String(deserializer);
    var var_listenPortStart = sse_decode_u_16(deserializer);
    var var_listenPortEnd = sse_decode_u_16(deserializer);
    var var_enableUpnpPortForwarding = sse_decode_bool(deserializer);
    var var_socksProxyUrl = sse_decode_opt_String(deserializer);
    var var_disableDht = sse_decode_bool(deserializer);
    var var_disableDhtPersistence = sse_decode_bool(deserializer);
    var var_persistSession = sse_decode_bool(deserializer);
    var var_fastresume = sse_decode_bool(deserializer);
    var var_deferWritesUpToMb = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_concurrentInitLimit = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_peerConnectTimeoutSecs =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_peerReadWriteTimeoutSecs =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_peerKeepAliveIntervalSecs =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_blocklistUrl = sse_decode_opt_String(deserializer);
    var var_trackers = sse_decode_list_String(deserializer);
    return EngineSettings(
        uploadLimitBps: var_uploadLimitBps,
        downloadLimitBps: var_downloadLimitBps,
        downloadDir: var_downloadDir,
        listenPortStart: var_listenPortStart,
        listenPortEnd: var_listenPortEnd,
        enableUpnpPortForwarding: var_enableUpnpPortForwarding,
        socksProxyUrl: var_socksProxyUrl,
        disableDht: var_disableDht,
        disableDhtPersistence: var_disableDhtPersistence,
        persistSession: var_persistSession,
        fastresume: var_fastresume,
        deferWritesUpToMb: var_deferWritesUpToMb,
        concurrentInitLimit: var_concurrentInitLimit,
        peerConnectTimeoutSecs: var_peerConnectTimeoutSecs,
        peerReadWriteTimeoutSecs: var_peerReadWriteTimeoutSecs,
        peerKeepAliveIntervalSecs: var_peerKeepAliveIntervalSecs,
        blocklistUrl: var_blocklistUrl,
        trackers: var_trackers);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppCollection> sse_decode_list_app_collection(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppCollection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_collection(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppContact> sse_decode_list_app_contact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppContact>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_contact(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppEntry> sse_decode_list_app_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppSourceFile> sse_decode_list_app_source_file(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppSourceFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_source_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppStorageEntry> sse_decode_list_app_storage_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppStorageEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_storage_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<PieceRun> sse_decode_list_piece_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PieceRun>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_piece_run(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SourceFile> sse_decode_list_source_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SourceFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_source_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorrentFile> sse_decode_list_torrent_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorrentInfo> sse_decode_list_torrent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_info(deserializer));
    }
    return ans_;
  }

  @protected
  NexusEndpointConfig sse_decode_nexus_endpoint_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_opt_String(deserializer);
    var var_directAddress = sse_decode_opt_String(deserializer);
    return NexusEndpointConfig(
        nodeId: var_nodeId, directAddress: var_directAddress);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AppDetail? sse_decode_opt_box_autoadd_app_detail(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_app_detail(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AppPending? sse_decode_opt_box_autoadd_app_pending(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_app_pending(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AppTransfer? sse_decode_opt_box_autoadd_app_transfer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_app_transfer(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PieceRun sse_decode_piece_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offsetBytes = sse_decode_u_64(deserializer);
    var var_lengthBytes = sse_decode_u_64(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    var var_peers = sse_decode_list_String(deserializer);
    return PieceRun(
        offsetBytes: var_offsetBytes,
        lengthBytes: var_lengthBytes,
        verified: var_verified,
        peers: var_peers);
  }

  @protected
  SourceFile sse_decode_source_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_lengthBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    return SourceFile(
        name: var_name, path: var_path, lengthBytes: var_lengthBytes);
  }

  @protected
  TorrentFile sse_decode_torrent_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_absolutePath = sse_decode_String(deserializer);
    var var_lengthBytes = sse_decode_u_64(deserializer);
    var var_downloadedBytes = sse_decode_u_64(deserializer);
    var var_pieceRuns = sse_decode_list_piece_run(deserializer);
    return TorrentFile(
        name: var_name,
        absolutePath: var_absolutePath,
        lengthBytes: var_lengthBytes,
        downloadedBytes: var_downloadedBytes,
        pieceRuns: var_pieceRuns);
  }

  @protected
  TorrentInfo sse_decode_torrent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_usize(deserializer);
    var var_infoHash = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_progressBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_uploadedBytes = sse_decode_u_64(deserializer);
    var var_downloadMbps = sse_decode_f_64(deserializer);
    var var_uploadMbps = sse_decode_f_64(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_files = sse_decode_list_torrent_file(deserializer);
    var var_livePeers = sse_decode_u_32(deserializer);
    var var_livePeerAddrs = sse_decode_list_String(deserializer);
    return TorrentInfo(
        id: var_id,
        infoHash: var_infoHash,
        name: var_name,
        state: var_state,
        progressBytes: var_progressBytes,
        totalBytes: var_totalBytes,
        uploadedBytes: var_uploadedBytes,
        downloadMbps: var_downloadMbps,
        uploadMbps: var_uploadMbps,
        finished: var_finished,
        error: var_error,
        files: var_files,
        livePeers: var_livePeers,
        livePeerAddrs: var_livePeerAddrs);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_app_snapshot_Sse(
      RustStreamSink<AppSnapshot> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_app_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_app_detail_Sse(
      RustStreamSink<AppDetail?> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_app_detail,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_accepted(AppAccepted self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_opt_box_autoadd_u_32(self.collection, serializer);
    sse_encode_bool(self.queued, serializer);
  }

  @protected
  void sse_encode_app_collection(AppCollection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.nature, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_u_64(self.revision, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_list_prim_u_32_strict(self.members, serializer);
    sse_encode_u_32(self.entries, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.onDiskBytes, serializer);
    sse_encode_u_64(self.uploadedBytes, serializer);
    sse_encode_opt_box_autoadd_u_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_u_64(self.completedAt, serializer);
    sse_encode_opt_box_autoadd_app_transfer(self.transfer, serializer);
    sse_encode_opt_box_autoadd_app_pending(self.pending, serializer);
  }

  @protected
  void sse_encode_app_command(AppCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_list_app_source_file(self.files, serializer);
    sse_encode_opt_box_autoadd_u_32(self.collection, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_opt_box_autoadd_bool(self.deleteFiles, serializer);
    sse_encode_opt_box_autoadd_u_32(self.entry, serializer);
    sse_encode_opt_String(self.source, serializer);
    sse_encode_list_prim_u_32_strict(self.entries, serializer);
    sse_encode_opt_box_autoadd_u_32(self.contact, serializer);
    sse_encode_opt_String(self.handle, serializer);
    sse_encode_opt_box_autoadd_bool(self.accept, serializer);
    sse_encode_opt_box_autoadd_u_32(self.device, serializer);
    sse_encode_opt_box_autoadd_bool(self.active, serializer);
    sse_encode_opt_box_autoadd_bool(self.paused, serializer);
  }

  @protected
  void sse_encode_app_contact(AppContact self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_opt_String(self.handle, serializer);
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_bool(self.verified, serializer);
    sse_encode_String(self.friendship, serializer);
    sse_encode_opt_String(self.reachable, serializer);
  }

  @protected
  void sse_encode_app_detail(AppDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_list_app_entry(self.entries, serializer);
    sse_encode_list_prim_u_8_strict(self.pieces, serializer);
    sse_encode_list_prim_u_8_strict(self.samples, serializer);
    sse_encode_list_String(self.peers, serializer);
  }

  @protected
  void sse_encode_app_device(AppDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.handle, serializer);
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_u_32(self.devices, serializer);
  }

  @protected
  void sse_encode_app_entry(AppEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_u_64(self.bytes, serializer);
    sse_encode_bool(self.selected, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_u_64(self.downloadedBytes, serializer);
    sse_encode_opt_String(self.path, serializer);
  }

  @protected
  void sse_encode_app_pending(AppPending self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.command, serializer);
    sse_encode_bool(self.queued, serializer);
  }

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_device(self.device, serializer);
    sse_encode_String(self.connectivity, serializer);
    sse_encode_list_app_contact(self.contacts, serializer);
    sse_encode_list_app_collection(self.collections, serializer);
    sse_encode_list_String(self.alerts, serializer);
  }

  @protected
  void sse_encode_app_source_file(
      AppSourceFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.bytes, serializer);
  }

  @protected
  void sse_encode_app_storage_entry(
      AppStorageEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.bytes, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_box_autoadd_u_32(self.collection, serializer);
    sse_encode_opt_String(self.collectionName, serializer);
  }

  @protected
  void sse_encode_app_transfer(AppTransfer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.progress, serializer);
    sse_encode_u_32(self.downBytesPerSecond, serializer);
    sse_encode_u_32(self.upBytesPerSecond, serializer);
    sse_encode_u_16(self.peers, serializer);
    sse_encode_opt_box_autoadd_u_32(self.etaSecs, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_command(
      AppCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_app_detail(
      AppDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_detail(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_app_pending(
      AppPending self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_pending(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_app_transfer(
      AppTransfer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_transfer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_engine_settings(
      EngineSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_engine_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_nexus_endpoint_config(
      NexusEndpointConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_nexus_endpoint_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_torrent_info(
      TorrentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_torrent_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_device_identity_info(
      DeviceIdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.nickname, serializer);
  }

  @protected
  void sse_encode_engine_settings(
      EngineSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.uploadLimitBps, serializer);
    sse_encode_opt_box_autoadd_u_32(self.downloadLimitBps, serializer);
    sse_encode_opt_String(self.downloadDir, serializer);
    sse_encode_u_16(self.listenPortStart, serializer);
    sse_encode_u_16(self.listenPortEnd, serializer);
    sse_encode_bool(self.enableUpnpPortForwarding, serializer);
    sse_encode_opt_String(self.socksProxyUrl, serializer);
    sse_encode_bool(self.disableDht, serializer);
    sse_encode_bool(self.disableDhtPersistence, serializer);
    sse_encode_bool(self.persistSession, serializer);
    sse_encode_bool(self.fastresume, serializer);
    sse_encode_opt_box_autoadd_u_32(self.deferWritesUpToMb, serializer);
    sse_encode_opt_box_autoadd_u_32(self.concurrentInitLimit, serializer);
    sse_encode_opt_box_autoadd_u_32(self.peerConnectTimeoutSecs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.peerReadWriteTimeoutSecs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.peerKeepAliveIntervalSecs, serializer);
    sse_encode_opt_String(self.blocklistUrl, serializer);
    sse_encode_list_String(self.trackers, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_collection(
      List<AppCollection> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_collection(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_contact(
      List<AppContact> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_contact(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_entry(
      List<AppEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_source_file(
      List<AppSourceFile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_source_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_storage_entry(
      List<AppStorageEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_storage_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_piece_run(
      List<PieceRun> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_piece_run(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_source_file(
      List<SourceFile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_source_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torrent_file(
      List<TorrentFile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torrent_info(
      List<TorrentInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_info(item, serializer);
    }
  }

  @protected
  void sse_encode_nexus_endpoint_config(
      NexusEndpointConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.nodeId, serializer);
    sse_encode_opt_String(self.directAddress, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_app_detail(
      AppDetail? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_app_detail(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_app_pending(
      AppPending? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_app_pending(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_app_transfer(
      AppTransfer? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_app_transfer(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_piece_run(PieceRun self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.offsetBytes, serializer);
    sse_encode_u_64(self.lengthBytes, serializer);
    sse_encode_bool(self.verified, serializer);
    sse_encode_list_String(self.peers, serializer);
  }

  @protected
  void sse_encode_source_file(SourceFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lengthBytes, serializer);
  }

  @protected
  void sse_encode_torrent_file(TorrentFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.absolutePath, serializer);
    sse_encode_u_64(self.lengthBytes, serializer);
    sse_encode_u_64(self.downloadedBytes, serializer);
    sse_encode_list_piece_run(self.pieceRuns, serializer);
  }

  @protected
  void sse_encode_torrent_info(TorrentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.id, serializer);
    sse_encode_String(self.infoHash, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_u_64(self.progressBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.uploadedBytes, serializer);
    sse_encode_f_64(self.downloadMbps, serializer);
    sse_encode_f_64(self.uploadMbps, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_list_torrent_file(self.files, serializer);
    sse_encode_u_32(self.livePeers, serializer);
    sse_encode_list_String(self.livePeerAddrs, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
