// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_service`, `endpoint_addr`, `normalise`, `normalized`, `present`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// The Nexus service this build talks to.
///
/// There is nothing to load. The service is the same one for everybody and is
/// compiled in, so this is a constant read through the same validation as any
/// other endpoint rather than a setting with a history.
///
/// It used to be stored, which meant an address written once outlived every
/// later change to what the default was — a device kept dialling a port
/// nothing had listened on for months, and the only way out was a screen
/// telling people to edit something they should never have been shown.
///
/// # Errors
///
/// Returns an error when the compiled-in service is not a valid endpoint,
/// which is a build mistake rather than anything a person did.
Future<NexusEndpointConfig> nexusEndpointConfig() =>
    RustLib.instance.api.crateNexusSettingsNexusEndpointConfig();

/// A trusted Nexus service the app may connect to.
///
/// The Node ID is the identity and is required; the direct address is an
/// optional hint. Discovery resolves a Node ID to an address on its own — over
/// mDNS on the same network, or a signed record on n0's name server anywhere
/// else — so an address is worth setting only to skip that lookup, or to reach
/// a service that publishes neither.
///
/// An address without a Node ID stays refused. A route to an unnamed service
/// discards the identity QUIC authenticates, which is the only thing making
/// the service the one the person meant.
class NexusEndpointConfig {
  /// The public QUIC Node ID logged by the Nexus service.
  final String? nodeId;

  /// An IP address and UDP port where that service can currently be reached,
  /// when discovery should not be relied on to find it.
  final String? directAddress;

  const NexusEndpointConfig({
    this.nodeId,
    this.directAddress,
  });

  static Future<NexusEndpointConfig> default_() =>
      RustLib.instance.api.crateNexusSettingsNexusEndpointConfigDefault();

  /// Whether this is the service the build ships with rather than a choice.
  ///
  /// Worth showing: "Portalis service" and "the one you typed in" deserve
  /// different words, and a person who has overridden the default should be
  /// able to see that they did.
  Future<bool> isDefaultService() => RustLib.instance.api
          .crateNexusSettingsNexusEndpointConfigIsDefaultService(
        that: this,
      );

  @override
  int get hashCode => nodeId.hashCode ^ directAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NexusEndpointConfig &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          directAddress == other.directAddress;
}
