// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// The settings the engine is configured with, loaded from disk (defaults on
/// first run).
Future<EngineSettings> engineSettings() =>
    RustLib.instance.api.crateNexusSettingsEngineSettings();

/// The built-in defaults, for a "reset" action in the UI.
Future<EngineSettings> defaultEngineSettings() =>
    RustLib.instance.api.crateNexusSettingsDefaultEngineSettings();

/// Persists `settings`, applying the live ones (rate limits) to the running
/// session straight away.
///
/// Returns `true` when a restart-required field changed *and* the session is
/// already running — i.e. the UI should tell the user the change lands next
/// launch. Returns `false` when everything asked for is already in effect.
Future<bool> setEngineSettings({required EngineSettings settings}) =>
    RustLib.instance.api
        .crateNexusSettingsSetEngineSettings(settings: settings);

/// The engine's full configuration surface. `serde(default)` throughout so a
/// `settings.json` written by an older build still loads.
class EngineSettings {
  /// Upload cap in bytes/sec across all torrents. `None` = unlimited.
  final int? uploadLimitBps;

  /// Download cap in bytes/sec across all torrents. `None` = unlimited.
  final int? downloadLimitBps;

  /// Root folder used for newly added torrents. `None` keeps Portalis's
  /// platform default (Downloads on desktop, Documents on mobile).
  final String? downloadDir;

  /// Range to pick the incoming-peer TCP port from. librqbit takes the
  /// first free port in it; with no range it binds *no* listener at all
  /// and nobody can download from this device.
  final int listenPortStart;
  final int listenPortEnd;

  /// Ask the router (UPnP/IGD) to forward the listen port. A no-op on
  /// routers with UPnP disabled, and impossible while a VPN owns the
  /// default route (discovery follows that route instead of reaching the
  /// router).
  final bool enableUpnpPortForwarding;

  /// `socks5://[user:pass@]host:port`. Routes peer traffic through a SOCKS5
  /// proxy.
  final String? socksProxyUrl;

  /// Turn off the distributed hash table. Peers can then only be found via
  /// trackers or addresses handed over directly.
  final bool disableDht;

  /// Stop reusing the stored DHT identity/port between runs. Off by
  /// default; note the stored port is why two instances of this app can't
  /// run at once.
  final bool disableDhtPersistence;

  /// Remember which torrents the session holds across restarts. Without it
  /// the engine starts empty every launch and silently stops seeding
  /// everything previously shared.
  final bool persistSession;

  /// Trust persisted piece state instead of re-hashing every file on
  /// launch, so collections resume seeding immediately.
  final bool fastresume;

  /// Buffer writes in memory up to roughly this many megabytes instead of
  /// writing straight through. `None` = write through.
  final int? deferWritesUpToMb;

  /// How many torrents may initialise concurrently. `None` = librqbit's
  /// default.
  final int? concurrentInitLimit;

  /// Per-peer connection timeouts, in seconds. `None` = librqbit's default.
  final int? peerConnectTimeoutSecs;
  final int? peerReadWriteTimeoutSecs;
  final int? peerKeepAliveIntervalSecs;

  /// URL of an IP blocklist to fetch and enforce.
  final String? blocklistUrl;

  /// Tracker URLs added to every torrent, on top of any it already carries.
  final List<String> trackers;

  const EngineSettings({
    this.uploadLimitBps,
    this.downloadLimitBps,
    this.downloadDir,
    required this.listenPortStart,
    required this.listenPortEnd,
    required this.enableUpnpPortForwarding,
    this.socksProxyUrl,
    required this.disableDht,
    required this.disableDhtPersistence,
    required this.persistSession,
    required this.fastresume,
    this.deferWritesUpToMb,
    this.concurrentInitLimit,
    this.peerConnectTimeoutSecs,
    this.peerReadWriteTimeoutSecs,
    this.peerKeepAliveIntervalSecs,
    this.blocklistUrl,
    required this.trackers,
  });

  static Future<EngineSettings> default_() =>
      RustLib.instance.api.crateNexusSettingsEngineSettingsDefault();

  @override
  int get hashCode =>
      uploadLimitBps.hashCode ^
      downloadLimitBps.hashCode ^
      downloadDir.hashCode ^
      listenPortStart.hashCode ^
      listenPortEnd.hashCode ^
      enableUpnpPortForwarding.hashCode ^
      socksProxyUrl.hashCode ^
      disableDht.hashCode ^
      disableDhtPersistence.hashCode ^
      persistSession.hashCode ^
      fastresume.hashCode ^
      deferWritesUpToMb.hashCode ^
      concurrentInitLimit.hashCode ^
      peerConnectTimeoutSecs.hashCode ^
      peerReadWriteTimeoutSecs.hashCode ^
      peerKeepAliveIntervalSecs.hashCode ^
      blocklistUrl.hashCode ^
      trackers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineSettings &&
          runtimeType == other.runtimeType &&
          uploadLimitBps == other.uploadLimitBps &&
          downloadLimitBps == other.downloadLimitBps &&
          downloadDir == other.downloadDir &&
          listenPortStart == other.listenPortStart &&
          listenPortEnd == other.listenPortEnd &&
          enableUpnpPortForwarding == other.enableUpnpPortForwarding &&
          socksProxyUrl == other.socksProxyUrl &&
          disableDht == other.disableDht &&
          disableDhtPersistence == other.disableDhtPersistence &&
          persistSession == other.persistSession &&
          fastresume == other.fastresume &&
          deferWritesUpToMb == other.deferWritesUpToMb &&
          concurrentInitLimit == other.concurrentInitLimit &&
          peerConnectTimeoutSecs == other.peerConnectTimeoutSecs &&
          peerReadWriteTimeoutSecs == other.peerReadWriteTimeoutSecs &&
          peerKeepAliveIntervalSecs == other.peerKeepAliveIntervalSecs &&
          blocklistUrl == other.blocklistUrl &&
          trackers == other.trackers;
}
