// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `acquire_selection`, `advance_hashing`, `advance`, `cancel`, `complete_final_piece`, `download_dir`, `ensure_active`, `forget_torrent`, `inspect_source_files`, `inspect_source`, `is_magnet`, `is_remote_source`, `is_torrent_path`, `make_source_names_unique`, `new`, `numbered_source_name`, `pause_torrent`, `publish`, `restart_torrent`, `session_started`, `set_rate_limits`, `set_selection`, `set_stage`, `storage_breakdown`, `validate_source_files`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PublishProgressState`, `PublishProgress`, `RawStorageEntry`, `TorrentMetadataFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Create a new collection by linking local files into a torrent layout,
/// building a `.torrent` from that layout and adding it back to the session at
/// the same location — since the files are already there and match the
/// piece hashes just computed from them, librqbit verifies them as already
/// complete and starts seeding immediately, no download needed. This is
/// the "share something" side of the app; `add_torrent_from_*` above is
/// the "join a swarm" side — both produce the exact same `TorrentInfo`
/// shape either way (see the backend README on why: it's the same
/// protocol regardless of which side of the swarm you started on).
Future<TorrentInfo> createCollection(
        {required String name, required List<SourceFile> files}) =>
    RustLib.instance.api.crateTorrentCreateCollection(name: name, files: files);

/// Add a torrent from a magnet link (or bare 40-char info-hash, which
/// `librqbit` also accepts as a magnet-equivalent).
Future<TorrentInfo> addTorrentFromMagnet({required String magnetOrHash}) =>
    RustLib.instance.api
        .crateTorrentAddTorrentFromMagnet(magnetOrHash: magnetOrHash);

/// Add a `.torrent` file without loading its metadata into Dart first.
Future<TorrentInfo> addTorrentFromFilePath({required String path}) =>
    RustLib.instance.api.crateTorrentAddTorrentFromFilePath(path: path);

/// Snapshot of every torrent currently managed by the debug session. The
/// Flutter side polls this on a timer — this is a smoke test, not the
/// push-based `watch_*` design the real Collections API will use.
Future<List<TorrentInfo>> listTorrents() =>
    RustLib.instance.api.crateTorrentListTorrents();

/// Where downloaded files actually land, so the UI can show the user a real
/// path instead of leaving them to guess (this was a temp directory before —
/// invisible in practice). A real desktop `MediaStorageSink` (see the
/// backend README) will replace this later; for this smoke test it's just
/// the platform Downloads folder.
Future<String> outputDir() => RustLib.instance.api.crateTorrentOutputDir();

/// Real disk usage of everything downloaded/shared so far — the Settings
/// screen's storage meter. Recursive over `output_dir()`.
Future<BigInt> storageUsageBytes() =>
    RustLib.instance.api.crateTorrentStorageUsageBytes();

class PieceRun {
  final BigInt offsetBytes;
  final BigInt lengthBytes;
  final bool verified;

  /// Real peers assigned to the intersecting in-flight piece. Empty for a
  /// verified run; peer identity is only its current network address.
  final List<String> peers;

  const PieceRun({
    required this.offsetBytes,
    required this.lengthBytes,
    required this.verified,
    required this.peers,
  });

  @override
  int get hashCode =>
      offsetBytes.hashCode ^
      lengthBytes.hashCode ^
      verified.hashCode ^
      peers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PieceRun &&
          runtimeType == other.runtimeType &&
          offsetBytes == other.offsetBytes &&
          lengthBytes == other.lengthBytes &&
          verified == other.verified &&
          peers == other.peers;
}

/// One native file Rust will publish as torrent content.
///
/// Only the path crosses the Flutter boundary. Rust owns reading, hashing,
/// torrent construction, and seeding, so file size is never limited by Dart
/// memory or the bridge's signed 32-bit byte-vector encoding. Publication
/// links this source into its torrent layout; it never copies its bytes.
class SourceFile {
  final String name;
  final String path;
  final BigInt? lengthBytes;

  const SourceFile({
    required this.name,
    required this.path,
    this.lengthBytes,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ lengthBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          lengthBytes == other.lengthBytes;
}

/// One file inside a torrent, with its real on-disk location — resolved via
/// `librqbit::Api` (which knows the actual per-torrent output folder,
/// including the subfolder it auto-creates for multi-file torrents) rather
/// than guessed, so Flutter can load a thumbnail or open/play it directly.
class TorrentFile {
  final String name;
  final String absolutePath;
  final BigInt lengthBytes;
  final BigInt downloadedBytes;

  /// File-relative intersections of verified and currently downloading
  /// torrent pieces. Missing ranges are implicit.
  final List<PieceRun> pieceRuns;

  const TorrentFile({
    required this.name,
    required this.absolutePath,
    required this.lengthBytes,
    required this.downloadedBytes,
    required this.pieceRuns,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      absolutePath.hashCode ^
      lengthBytes.hashCode ^
      downloadedBytes.hashCode ^
      pieceRuns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          absolutePath == other.absolutePath &&
          lengthBytes == other.lengthBytes &&
          downloadedBytes == other.downloadedBytes &&
          pieceRuns == other.pieceRuns;
}

class TorrentInfo {
  final BigInt id;
  final String infoHash;
  final String name;
  final String state;

  /// Bytes confirmed present, or zero while the engine is still checking
  /// and does not yet know. Use [`TorrentInfo::knows_progress`] before
  /// treating a zero here as a measurement.
  final BigInt progressBytes;
  final BigInt totalBytes;
  final BigInt uploadedBytes;
  final double downloadMbps;
  final double uploadMbps;
  final bool finished;
  final String? error;
  final List<TorrentFile> files;

  /// Currently-connected peers (not the historical total ever seen) — the
  /// closest real equivalent to the mockup's "N copies alive" indicator.
  final int livePeers;

  /// `"ip:port"` of each currently-connected peer. BitTorrent peers carry
  /// no identity beyond their network address — there is no name, no
  /// signed device id, nothing to correlate them with a collaborator.
  final List<String> livePeerAddrs;

  const TorrentInfo({
    required this.id,
    required this.infoHash,
    required this.name,
    required this.state,
    required this.progressBytes,
    required this.totalBytes,
    required this.uploadedBytes,
    required this.downloadMbps,
    required this.uploadMbps,
    required this.finished,
    this.error,
    required this.files,
    required this.livePeers,
    required this.livePeerAddrs,
  });

  /// Whether [`Self::progress_bytes`] is a measurement rather than a
  /// placeholder.
  ///
  /// A torrent being verified reports nothing rather than the scan cursor,
  /// which would climb to full and then collapse. Correct for a status, and
  /// wrong to record: written into the history it became a zero between two
  /// real readings, and a chart drew the transfer as having restarted.
  Future<bool> knowsProgress() =>
      RustLib.instance.api.crateTorrentTorrentInfoKnowsProgress(
        that: this,
      );

  @override
  int get hashCode =>
      id.hashCode ^
      infoHash.hashCode ^
      name.hashCode ^
      state.hashCode ^
      progressBytes.hashCode ^
      totalBytes.hashCode ^
      uploadedBytes.hashCode ^
      downloadMbps.hashCode ^
      uploadMbps.hashCode ^
      finished.hashCode ^
      error.hashCode ^
      files.hashCode ^
      livePeers.hashCode ^
      livePeerAddrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          infoHash == other.infoHash &&
          name == other.name &&
          state == other.state &&
          progressBytes == other.progressBytes &&
          totalBytes == other.totalBytes &&
          uploadedBytes == other.uploadedBytes &&
          downloadMbps == other.downloadMbps &&
          uploadMbps == other.uploadMbps &&
          finished == other.finished &&
          error == other.error &&
          files == other.files &&
          livePeers == other.livePeers &&
          livePeerAddrs == other.livePeerAddrs;
}
