[package]
name = "portalis-nexus-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
flate2.workspace = true
hkdf.workspace = true
sha2.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true
x25519-dalek.workspace = true

[lints]
workspace = true

[dev-dependencies]
image = { version = "0.25.9", default-features = false }
qrcode = { version = "0.14.1", default-features = false, features = ["image"] }
rqrr = "0.10.1"
url = "2.5.8"
