// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1414326327;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__settings__default_engine_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "default_engine_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::settings::default_engine_settings())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__device__device_identity_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "device_identity",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::device::device_identity()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__settings__engine_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::settings::engine_settings()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__settings__engine_settings_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_settings_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::settings::EngineSettings::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__bridge__get_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::bridge::get_version())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__nexus_settings__nexus_endpoint_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "nexus_endpoint_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::nexus_settings::nexus_endpoint_config()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__nexus_settings__nexus_endpoint_config_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "nexus_endpoint_config_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::nexus_settings::NexusEndpointConfig::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__nexus_settings__nexus_endpoint_config_is_default_service_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "nexus_endpoint_config_is_default_service",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that =
                <crate::nexus_settings::NexusEndpointConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::nexus_settings::NexusEndpointConfig::is_default_service(&api_that),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__portalis_api__send_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_command = <crate::portalis_api::AppCommand>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::portalis_api::send(api_command)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__portalis_api__set_active_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_active",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_active = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::portalis_api::set_active(api_active)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__settings__set_engine_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_engine_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_settings = <crate::settings::EngineSettings>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::settings::set_engine_settings(api_settings).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__device__set_nickname_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_nickname",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_nickname = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::device::set_nickname(api_nickname)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__portalis_api__start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::portalis_api::start().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__portalis_api__stop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::portalis_api::stop().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__portalis_api__storage_breakdown_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "storage_breakdown",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::portalis_api::storage_breakdown().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__portalis_api__watch_detail_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "watch_detail",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_collection = <Option<u32>>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                Option<crate::portalis_api::AppDetail>,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::portalis_api::watch_detail(api_collection, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__portalis_api__watch_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "watch_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_collection = <u32>::sse_decode(&mut deserializer);
            let api_sink =
                <StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(
                    &mut deserializer,
                );
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::portalis_api::watch_history(api_collection, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__portalis_api__watch_states_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "watch_states",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::portalis_api::AppSnapshot,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::portalis_api::watch_states(api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::portalis_api::AppSnapshot, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        Option<crate::portalis_api::AppDetail>,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::portalis_api::AppAccepted {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u64>::sse_decode(deserializer);
        let mut var_collection = <Option<u32>>::sse_decode(deserializer);
        let mut var_queued = <bool>::sse_decode(deserializer);
        return crate::portalis_api::AppAccepted {
            id: var_id,
            collection: var_collection,
            queued: var_queued,
        };
    }
}

impl SseDecode for crate::portalis_api::AppCollection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u32>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_nature = <String>::sse_decode(deserializer);
        let mut var_role = <String>::sse_decode(deserializer);
        let mut var_revision = <u64>::sse_decode(deserializer);
        let mut var_status = <String>::sse_decode(deserializer);
        let mut var_members = <Vec<u32>>::sse_decode(deserializer);
        let mut var_entries = <u32>::sse_decode(deserializer);
        let mut var_totalBytes = <u64>::sse_decode(deserializer);
        let mut var_onDiskBytes = <u64>::sse_decode(deserializer);
        let mut var_uploadedBytes = <u64>::sse_decode(deserializer);
        let mut var_startedAt = <Option<u64>>::sse_decode(deserializer);
        let mut var_completedAt = <Option<u64>>::sse_decode(deserializer);
        let mut var_transfer = <Option<crate::portalis_api::AppTransfer>>::sse_decode(deserializer);
        let mut var_pending = <Option<crate::portalis_api::AppPending>>::sse_decode(deserializer);
        return crate::portalis_api::AppCollection {
            id: var_id,
            name: var_name,
            nature: var_nature,
            role: var_role,
            revision: var_revision,
            status: var_status,
            members: var_members,
            entries: var_entries,
            total_bytes: var_totalBytes,
            on_disk_bytes: var_onDiskBytes,
            uploaded_bytes: var_uploadedBytes,
            started_at: var_startedAt,
            completed_at: var_completedAt,
            transfer: var_transfer,
            pending: var_pending,
        };
    }
}

impl SseDecode for crate::portalis_api::AppCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_files = <Vec<crate::portalis_api::AppSourceFile>>::sse_decode(deserializer);
        let mut var_collection = <Option<u32>>::sse_decode(deserializer);
        let mut var_label = <Option<String>>::sse_decode(deserializer);
        let mut var_deleteFiles = <Option<bool>>::sse_decode(deserializer);
        let mut var_entry = <Option<u32>>::sse_decode(deserializer);
        let mut var_source = <Option<String>>::sse_decode(deserializer);
        let mut var_entries = <Vec<u32>>::sse_decode(deserializer);
        let mut var_contact = <Option<u32>>::sse_decode(deserializer);
        let mut var_handle = <Option<String>>::sse_decode(deserializer);
        let mut var_accept = <Option<bool>>::sse_decode(deserializer);
        let mut var_device = <Option<u32>>::sse_decode(deserializer);
        let mut var_active = <Option<bool>>::sse_decode(deserializer);
        let mut var_paused = <Option<bool>>::sse_decode(deserializer);
        return crate::portalis_api::AppCommand {
            kind: var_kind,
            name: var_name,
            files: var_files,
            collection: var_collection,
            label: var_label,
            delete_files: var_deleteFiles,
            entry: var_entry,
            source: var_source,
            entries: var_entries,
            contact: var_contact,
            handle: var_handle,
            accept: var_accept,
            device: var_device,
            active: var_active,
            paused: var_paused,
        };
    }
}

impl SseDecode for crate::portalis_api::AppContact {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u32>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_handle = <Option<String>>::sse_decode(deserializer);
        let mut var_fingerprint = <String>::sse_decode(deserializer);
        let mut var_verified = <bool>::sse_decode(deserializer);
        let mut var_friendship = <String>::sse_decode(deserializer);
        let mut var_reachable = <Option<String>>::sse_decode(deserializer);
        return crate::portalis_api::AppContact {
            id: var_id,
            display_name: var_displayName,
            handle: var_handle,
            fingerprint: var_fingerprint,
            verified: var_verified,
            friendship: var_friendship,
            reachable: var_reachable,
        };
    }
}

impl SseDecode for crate::portalis_api::AppDetail {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u32>::sse_decode(deserializer);
        let mut var_entries = <Vec<crate::portalis_api::AppEntry>>::sse_decode(deserializer);
        let mut var_pieces = <Vec<u8>>::sse_decode(deserializer);
        let mut var_peers = <Vec<String>>::sse_decode(deserializer);
        return crate::portalis_api::AppDetail {
            id: var_id,
            entries: var_entries,
            pieces: var_pieces,
            peers: var_peers,
        };
    }
}

impl SseDecode for crate::portalis_api::AppDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_handle = <Option<String>>::sse_decode(deserializer);
        let mut var_fingerprint = <String>::sse_decode(deserializer);
        let mut var_devices = <u32>::sse_decode(deserializer);
        return crate::portalis_api::AppDevice {
            name: var_name,
            handle: var_handle,
            fingerprint: var_fingerprint,
            devices: var_devices,
        };
    }
}

impl SseDecode for crate::portalis_api::AppEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u32>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_bytes = <u64>::sse_decode(deserializer);
        let mut var_selected = <bool>::sse_decode(deserializer);
        let mut var_available = <bool>::sse_decode(deserializer);
        let mut var_downloadedBytes = <u64>::sse_decode(deserializer);
        let mut var_path = <Option<String>>::sse_decode(deserializer);
        return crate::portalis_api::AppEntry {
            id: var_id,
            label: var_label,
            bytes: var_bytes,
            selected: var_selected,
            available: var_available,
            downloaded_bytes: var_downloadedBytes,
            path: var_path,
        };
    }
}

impl SseDecode for crate::portalis_api::AppPending {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_command = <u64>::sse_decode(deserializer);
        let mut var_queued = <bool>::sse_decode(deserializer);
        return crate::portalis_api::AppPending {
            command: var_command,
            queued: var_queued,
        };
    }
}

impl SseDecode for crate::portalis_api::AppSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_device = <crate::portalis_api::AppDevice>::sse_decode(deserializer);
        let mut var_connectivity = <String>::sse_decode(deserializer);
        let mut var_contacts = <Vec<crate::portalis_api::AppContact>>::sse_decode(deserializer);
        let mut var_collections =
            <Vec<crate::portalis_api::AppCollection>>::sse_decode(deserializer);
        let mut var_alerts = <Vec<String>>::sse_decode(deserializer);
        return crate::portalis_api::AppSnapshot {
            device: var_device,
            connectivity: var_connectivity,
            contacts: var_contacts,
            collections: var_collections,
            alerts: var_alerts,
        };
    }
}

impl SseDecode for crate::portalis_api::AppSourceFile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_bytes = <u64>::sse_decode(deserializer);
        return crate::portalis_api::AppSourceFile {
            name: var_name,
            path: var_path,
            bytes: var_bytes,
        };
    }
}

impl SseDecode for crate::portalis_api::AppStorageEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_bytes = <u64>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_collection = <Option<u32>>::sse_decode(deserializer);
        let mut var_collectionName = <Option<String>>::sse_decode(deserializer);
        return crate::portalis_api::AppStorageEntry {
            name: var_name,
            bytes: var_bytes,
            path: var_path,
            collection: var_collection,
            collection_name: var_collectionName,
        };
    }
}

impl SseDecode for crate::portalis_api::AppTransfer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_progress = <f32>::sse_decode(deserializer);
        let mut var_downBytesPerSecond = <u32>::sse_decode(deserializer);
        let mut var_upBytesPerSecond = <u32>::sse_decode(deserializer);
        let mut var_peers = <u16>::sse_decode(deserializer);
        let mut var_etaSecs = <Option<u32>>::sse_decode(deserializer);
        return crate::portalis_api::AppTransfer {
            progress: var_progress,
            down_bytes_per_second: var_downBytesPerSecond,
            up_bytes_per_second: var_upBytesPerSecond,
            peers: var_peers,
            eta_secs: var_etaSecs,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::device::DeviceIdentityInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_nickname = <String>::sse_decode(deserializer);
        return crate::device::DeviceIdentityInfo {
            device_id: var_deviceId,
            nickname: var_nickname,
        };
    }
}

impl SseDecode for crate::settings::EngineSettings {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_uploadLimitBps = <Option<u32>>::sse_decode(deserializer);
        let mut var_downloadLimitBps = <Option<u32>>::sse_decode(deserializer);
        let mut var_downloadDir = <Option<String>>::sse_decode(deserializer);
        let mut var_listenPortStart = <u16>::sse_decode(deserializer);
        let mut var_listenPortEnd = <u16>::sse_decode(deserializer);
        let mut var_enableUpnpPortForwarding = <bool>::sse_decode(deserializer);
        let mut var_socksProxyUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_disableDht = <bool>::sse_decode(deserializer);
        let mut var_disableDhtPersistence = <bool>::sse_decode(deserializer);
        let mut var_persistSession = <bool>::sse_decode(deserializer);
        let mut var_fastresume = <bool>::sse_decode(deserializer);
        let mut var_deferWritesUpToMb = <Option<u32>>::sse_decode(deserializer);
        let mut var_concurrentInitLimit = <Option<u32>>::sse_decode(deserializer);
        let mut var_peerConnectTimeoutSecs = <Option<u32>>::sse_decode(deserializer);
        let mut var_peerReadWriteTimeoutSecs = <Option<u32>>::sse_decode(deserializer);
        let mut var_peerKeepAliveIntervalSecs = <Option<u32>>::sse_decode(deserializer);
        let mut var_blocklistUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_trackers = <Vec<String>>::sse_decode(deserializer);
        return crate::settings::EngineSettings {
            upload_limit_bps: var_uploadLimitBps,
            download_limit_bps: var_downloadLimitBps,
            download_dir: var_downloadDir,
            listen_port_start: var_listenPortStart,
            listen_port_end: var_listenPortEnd,
            enable_upnp_port_forwarding: var_enableUpnpPortForwarding,
            socks_proxy_url: var_socksProxyUrl,
            disable_dht: var_disableDht,
            disable_dht_persistence: var_disableDhtPersistence,
            persist_session: var_persistSession,
            fastresume: var_fastresume,
            defer_writes_up_to_mb: var_deferWritesUpToMb,
            concurrent_init_limit: var_concurrentInitLimit,
            peer_connect_timeout_secs: var_peerConnectTimeoutSecs,
            peer_read_write_timeout_secs: var_peerReadWriteTimeoutSecs,
            peer_keep_alive_interval_secs: var_peerKeepAliveIntervalSecs,
            blocklist_url: var_blocklistUrl,
            trackers: var_trackers,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::portalis_api::AppCollection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::portalis_api::AppCollection>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::portalis_api::AppContact> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::portalis_api::AppContact>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::portalis_api::AppEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::portalis_api::AppEntry>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::portalis_api::AppSourceFile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::portalis_api::AppSourceFile>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::portalis_api::AppStorageEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::portalis_api::AppStorageEntry>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::nexus_settings::NexusEndpointConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_nodeId = <Option<String>>::sse_decode(deserializer);
        let mut var_directAddress = <Option<String>>::sse_decode(deserializer);
        return crate::nexus_settings::NexusEndpointConfig {
            node_id: var_nodeId,
            direct_address: var_directAddress,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::portalis_api::AppDetail> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::portalis_api::AppDetail>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::portalis_api::AppPending> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::portalis_api::AppPending>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::portalis_api::AppTransfer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::portalis_api::AppTransfer>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<bool>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__settings__default_engine_settings_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__device__device_identity_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__settings__engine_settings_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__settings__engine_settings_default_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__nexus_settings__nexus_endpoint_config_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__nexus_settings__nexus_endpoint_config_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__nexus_settings__nexus_endpoint_config_is_default_service_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__portalis_api__send_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__portalis_api__set_active_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__settings__set_engine_settings_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__device__set_nickname_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__portalis_api__start_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__portalis_api__stop_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__portalis_api__storage_breakdown_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__portalis_api__watch_detail_impl(port, ptr, rust_vec_len, data_len),
        17 => wire__crate__portalis_api__watch_history_impl(port, ptr, rust_vec_len, data_len),
        18 => wire__crate__portalis_api__watch_states_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        5 => wire__crate__bridge__get_version_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppAccepted {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.collection.into_into_dart().into_dart(),
            self.queued.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppAccepted
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppAccepted>
    for crate::portalis_api::AppAccepted
{
    fn into_into_dart(self) -> crate::portalis_api::AppAccepted {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppCollection {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.nature.into_into_dart().into_dart(),
            self.role.into_into_dart().into_dart(),
            self.revision.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.members.into_into_dart().into_dart(),
            self.entries.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
            self.on_disk_bytes.into_into_dart().into_dart(),
            self.uploaded_bytes.into_into_dart().into_dart(),
            self.started_at.into_into_dart().into_dart(),
            self.completed_at.into_into_dart().into_dart(),
            self.transfer.into_into_dart().into_dart(),
            self.pending.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppCollection
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppCollection>
    for crate::portalis_api::AppCollection
{
    fn into_into_dart(self) -> crate::portalis_api::AppCollection {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppCommand {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.files.into_into_dart().into_dart(),
            self.collection.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.delete_files.into_into_dart().into_dart(),
            self.entry.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.entries.into_into_dart().into_dart(),
            self.contact.into_into_dart().into_dart(),
            self.handle.into_into_dart().into_dart(),
            self.accept.into_into_dart().into_dart(),
            self.device.into_into_dart().into_dart(),
            self.active.into_into_dart().into_dart(),
            self.paused.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppCommand
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppCommand>
    for crate::portalis_api::AppCommand
{
    fn into_into_dart(self) -> crate::portalis_api::AppCommand {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppContact {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.handle.into_into_dart().into_dart(),
            self.fingerprint.into_into_dart().into_dart(),
            self.verified.into_into_dart().into_dart(),
            self.friendship.into_into_dart().into_dart(),
            self.reachable.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppContact
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppContact>
    for crate::portalis_api::AppContact
{
    fn into_into_dart(self) -> crate::portalis_api::AppContact {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppDetail {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.entries.into_into_dart().into_dart(),
            self.pieces.into_into_dart().into_dart(),
            self.peers.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppDetail
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppDetail>
    for crate::portalis_api::AppDetail
{
    fn into_into_dart(self) -> crate::portalis_api::AppDetail {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppDevice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.handle.into_into_dart().into_dart(),
            self.fingerprint.into_into_dart().into_dart(),
            self.devices.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppDevice
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppDevice>
    for crate::portalis_api::AppDevice
{
    fn into_into_dart(self) -> crate::portalis_api::AppDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.bytes.into_into_dart().into_dart(),
            self.selected.into_into_dart().into_dart(),
            self.available.into_into_dart().into_dart(),
            self.downloaded_bytes.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::portalis_api::AppEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppEntry>
    for crate::portalis_api::AppEntry
{
    fn into_into_dart(self) -> crate::portalis_api::AppEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppPending {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.command.into_into_dart().into_dart(),
            self.queued.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppPending
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppPending>
    for crate::portalis_api::AppPending
{
    fn into_into_dart(self) -> crate::portalis_api::AppPending {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.device.into_into_dart().into_dart(),
            self.connectivity.into_into_dart().into_dart(),
            self.contacts.into_into_dart().into_dart(),
            self.collections.into_into_dart().into_dart(),
            self.alerts.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppSnapshot>
    for crate::portalis_api::AppSnapshot
{
    fn into_into_dart(self) -> crate::portalis_api::AppSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppSourceFile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppSourceFile
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppSourceFile>
    for crate::portalis_api::AppSourceFile
{
    fn into_into_dart(self) -> crate::portalis_api::AppSourceFile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppStorageEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.bytes.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.collection.into_into_dart().into_dart(),
            self.collection_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppStorageEntry
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppStorageEntry>
    for crate::portalis_api::AppStorageEntry
{
    fn into_into_dart(self) -> crate::portalis_api::AppStorageEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::portalis_api::AppTransfer {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.progress.into_into_dart().into_dart(),
            self.down_bytes_per_second.into_into_dart().into_dart(),
            self.up_bytes_per_second.into_into_dart().into_dart(),
            self.peers.into_into_dart().into_dart(),
            self.eta_secs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::portalis_api::AppTransfer
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::portalis_api::AppTransfer>
    for crate::portalis_api::AppTransfer
{
    fn into_into_dart(self) -> crate::portalis_api::AppTransfer {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::device::DeviceIdentityInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.device_id.into_into_dart().into_dart(),
            self.nickname.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::device::DeviceIdentityInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::device::DeviceIdentityInfo>
    for crate::device::DeviceIdentityInfo
{
    fn into_into_dart(self) -> crate::device::DeviceIdentityInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::settings::EngineSettings {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.upload_limit_bps.into_into_dart().into_dart(),
            self.download_limit_bps.into_into_dart().into_dart(),
            self.download_dir.into_into_dart().into_dart(),
            self.listen_port_start.into_into_dart().into_dart(),
            self.listen_port_end.into_into_dart().into_dart(),
            self.enable_upnp_port_forwarding
                .into_into_dart()
                .into_dart(),
            self.socks_proxy_url.into_into_dart().into_dart(),
            self.disable_dht.into_into_dart().into_dart(),
            self.disable_dht_persistence.into_into_dart().into_dart(),
            self.persist_session.into_into_dart().into_dart(),
            self.fastresume.into_into_dart().into_dart(),
            self.defer_writes_up_to_mb.into_into_dart().into_dart(),
            self.concurrent_init_limit.into_into_dart().into_dart(),
            self.peer_connect_timeout_secs.into_into_dart().into_dart(),
            self.peer_read_write_timeout_secs
                .into_into_dart()
                .into_dart(),
            self.peer_keep_alive_interval_secs
                .into_into_dart()
                .into_dart(),
            self.blocklist_url.into_into_dart().into_dart(),
            self.trackers.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::settings::EngineSettings
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::settings::EngineSettings>
    for crate::settings::EngineSettings
{
    fn into_into_dart(self) -> crate::settings::EngineSettings {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::nexus_settings::NexusEndpointConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.node_id.into_into_dart().into_dart(),
            self.direct_address.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::nexus_settings::NexusEndpointConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::nexus_settings::NexusEndpointConfig>
    for crate::nexus_settings::NexusEndpointConfig
{
    fn into_into_dart(self) -> crate::nexus_settings::NexusEndpointConfig {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::portalis_api::AppSnapshot, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for StreamSink<Vec<u8>, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        Option<crate::portalis_api::AppDetail>,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::portalis_api::AppAccepted {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.id, serializer);
        <Option<u32>>::sse_encode(self.collection, serializer);
        <bool>::sse_encode(self.queued, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppCollection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.nature, serializer);
        <String>::sse_encode(self.role, serializer);
        <u64>::sse_encode(self.revision, serializer);
        <String>::sse_encode(self.status, serializer);
        <Vec<u32>>::sse_encode(self.members, serializer);
        <u32>::sse_encode(self.entries, serializer);
        <u64>::sse_encode(self.total_bytes, serializer);
        <u64>::sse_encode(self.on_disk_bytes, serializer);
        <u64>::sse_encode(self.uploaded_bytes, serializer);
        <Option<u64>>::sse_encode(self.started_at, serializer);
        <Option<u64>>::sse_encode(self.completed_at, serializer);
        <Option<crate::portalis_api::AppTransfer>>::sse_encode(self.transfer, serializer);
        <Option<crate::portalis_api::AppPending>>::sse_encode(self.pending, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.name, serializer);
        <Vec<crate::portalis_api::AppSourceFile>>::sse_encode(self.files, serializer);
        <Option<u32>>::sse_encode(self.collection, serializer);
        <Option<String>>::sse_encode(self.label, serializer);
        <Option<bool>>::sse_encode(self.delete_files, serializer);
        <Option<u32>>::sse_encode(self.entry, serializer);
        <Option<String>>::sse_encode(self.source, serializer);
        <Vec<u32>>::sse_encode(self.entries, serializer);
        <Option<u32>>::sse_encode(self.contact, serializer);
        <Option<String>>::sse_encode(self.handle, serializer);
        <Option<bool>>::sse_encode(self.accept, serializer);
        <Option<u32>>::sse_encode(self.device, serializer);
        <Option<bool>>::sse_encode(self.active, serializer);
        <Option<bool>>::sse_encode(self.paused, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppContact {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <Option<String>>::sse_encode(self.handle, serializer);
        <String>::sse_encode(self.fingerprint, serializer);
        <bool>::sse_encode(self.verified, serializer);
        <String>::sse_encode(self.friendship, serializer);
        <Option<String>>::sse_encode(self.reachable, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppDetail {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.id, serializer);
        <Vec<crate::portalis_api::AppEntry>>::sse_encode(self.entries, serializer);
        <Vec<u8>>::sse_encode(self.pieces, serializer);
        <Vec<String>>::sse_encode(self.peers, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.handle, serializer);
        <String>::sse_encode(self.fingerprint, serializer);
        <u32>::sse_encode(self.devices, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
        <u64>::sse_encode(self.bytes, serializer);
        <bool>::sse_encode(self.selected, serializer);
        <bool>::sse_encode(self.available, serializer);
        <u64>::sse_encode(self.downloaded_bytes, serializer);
        <Option<String>>::sse_encode(self.path, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppPending {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.command, serializer);
        <bool>::sse_encode(self.queued, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::portalis_api::AppDevice>::sse_encode(self.device, serializer);
        <String>::sse_encode(self.connectivity, serializer);
        <Vec<crate::portalis_api::AppContact>>::sse_encode(self.contacts, serializer);
        <Vec<crate::portalis_api::AppCollection>>::sse_encode(self.collections, serializer);
        <Vec<String>>::sse_encode(self.alerts, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppSourceFile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.path, serializer);
        <u64>::sse_encode(self.bytes, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppStorageEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u64>::sse_encode(self.bytes, serializer);
        <String>::sse_encode(self.path, serializer);
        <Option<u32>>::sse_encode(self.collection, serializer);
        <Option<String>>::sse_encode(self.collection_name, serializer);
    }
}

impl SseEncode for crate::portalis_api::AppTransfer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.progress, serializer);
        <u32>::sse_encode(self.down_bytes_per_second, serializer);
        <u32>::sse_encode(self.up_bytes_per_second, serializer);
        <u16>::sse_encode(self.peers, serializer);
        <Option<u32>>::sse_encode(self.eta_secs, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::device::DeviceIdentityInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.nickname, serializer);
    }
}

impl SseEncode for crate::settings::EngineSettings {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<u32>>::sse_encode(self.upload_limit_bps, serializer);
        <Option<u32>>::sse_encode(self.download_limit_bps, serializer);
        <Option<String>>::sse_encode(self.download_dir, serializer);
        <u16>::sse_encode(self.listen_port_start, serializer);
        <u16>::sse_encode(self.listen_port_end, serializer);
        <bool>::sse_encode(self.enable_upnp_port_forwarding, serializer);
        <Option<String>>::sse_encode(self.socks_proxy_url, serializer);
        <bool>::sse_encode(self.disable_dht, serializer);
        <bool>::sse_encode(self.disable_dht_persistence, serializer);
        <bool>::sse_encode(self.persist_session, serializer);
        <bool>::sse_encode(self.fastresume, serializer);
        <Option<u32>>::sse_encode(self.defer_writes_up_to_mb, serializer);
        <Option<u32>>::sse_encode(self.concurrent_init_limit, serializer);
        <Option<u32>>::sse_encode(self.peer_connect_timeout_secs, serializer);
        <Option<u32>>::sse_encode(self.peer_read_write_timeout_secs, serializer);
        <Option<u32>>::sse_encode(self.peer_keep_alive_interval_secs, serializer);
        <Option<String>>::sse_encode(self.blocklist_url, serializer);
        <Vec<String>>::sse_encode(self.trackers, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::portalis_api::AppCollection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::portalis_api::AppCollection>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::portalis_api::AppContact> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::portalis_api::AppContact>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::portalis_api::AppEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::portalis_api::AppEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::portalis_api::AppSourceFile> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::portalis_api::AppSourceFile>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::portalis_api::AppStorageEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::portalis_api::AppStorageEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::nexus_settings::NexusEndpointConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.node_id, serializer);
        <Option<String>>::sse_encode(self.direct_address, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::portalis_api::AppDetail> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::portalis_api::AppDetail>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::portalis_api::AppPending> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::portalis_api::AppPending>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::portalis_api::AppTransfer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::portalis_api::AppTransfer>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <bool>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
