[package]
name = "portalis-nexus-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
portalis-nexus-client.workspace = true
portalis-nexus-server-core.workspace = true
futures-util.workspace = true
mongodb.workspace = true
portalis-nexus-protocol.workspace = true
tracing.workspace = true
redb.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
testcontainers-modules.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
